## Taxi Trajectory Prediction

Here are the links to papers and github repo with solution

https://arxiv.org/pdf/1508.00021.pdf  
https://github.com/adbrebs/taxi

In [1]:
! ls /home/ubuntu/taxi

arrival-clusters.pkl			    taxi1.ipynb   train.csv
arrivals.pkl				    test2pickle   val_idx.pkl
__MACOSX				    test.csv	  X_train.pkl
metaData_taxistandsID_name_GPSlocation.csv  tmp		  X_valid.pkl
models					    train2pickle


In [2]:
import torch

In [3]:
import pickle
from fastai.imports import *
from fastai.structured import *
from fastai.column_data import *
import torch.nn as nn
from fastai.dataset import *
from fastai.learner import *

In [4]:
path = "/home/ubuntu/taxi/"

In [47]:
# import zipfile
# zip_ref = zipfile.ZipFile('train.csv.zip', 'r')
# zip_ref.extractall(path)
# zip_ref.close()

In [48]:
train = pd.read_csv("train.csv")

In [49]:
test = pd.read_csv("test.csv")

In [50]:
train.head()

TRIP_ID CALL_TYPE  ORIGIN_CALL  ORIGIN_STAND   TAXI_ID  \
0  1372636858620000589         C          NaN           NaN  20000589   
1  1372637303620000596         B          NaN           7.0  20000596   
2  1372636951620000320         C          NaN           NaN  20000320   
3  1372636854620000520         C          NaN           NaN  20000520   
4  1372637091620000337         C          NaN           NaN  20000337   

    TIMESTAMP DAY_TYPE  MISSING_DATA  \
0  1372636858        A         False   
1  1372637303        A         False   
2  1372636951        A         False   
3  1372636854        A         False   
4  1372637091        A         False   

                                            POLYLINE  
0  [[-8.618643,41.141412],[-8.618499,41.141376],[...  
1  [[-8.639847,41.159826],[-8.640351,41.159871],[...  
2  [[-8.612964,41.140359],[-8.613378,41.14035],[-...  
3  [[-8.574678,41.151951],[-8.574705,41.151942],[...  
4  [[-8.645994,41.18049],[-8.645949,41.180517],[-...

In [51]:
list(train.POLYLINE[:1])

['[[-8.618643,41.141412],[-8.618499,41.141376],[-8.620326,41.14251],[-8.622153,41.143815],[-8.623953,41.144373],[-8.62668,41.144778],[-8.627373,41.144697],[-8.630226,41.14521],[-8.632746,41.14692],[-8.631738,41.148225],[-8.629938,41.150385],[-8.62911,41.151213],[-8.629128,41.15124],[-8.628786,41.152203],[-8.628687,41.152374],[-8.628759,41.152518],[-8.630838,41.15268],[-8.632323,41.153022],[-8.631144,41.154489],[-8.630829,41.154507],[-8.630829,41.154516],[-8.630829,41.154498],[-8.630838,41.154489]]']

In [52]:
list(test.POLYLINE[:1])

['[[-8.585676,41.148522],[-8.585712,41.148639],[-8.585685,41.148855],[-8.58573,41.148927],[-8.585982,41.148963],[-8.586396,41.148954],[-8.586072,41.14872],[-8.586324,41.147847],[-8.586999,41.14746],[-8.586576,41.147154],[-8.584884,41.146623]]']

In [53]:
test.head()

TRIP_ID CALL_TYPE  ORIGIN_CALL  ORIGIN_STAND   TAXI_ID   TIMESTAMP DAY_TYPE  \
0      T1         B          NaN          15.0  20000542  1408039037        A   
1      T2         B          NaN          57.0  20000108  1408038611        A   
2      T3         B          NaN          15.0  20000370  1408038568        A   
3      T4         B          NaN          53.0  20000492  1408039090        A   
4      T5         B          NaN          18.0  20000621  1408039177        A   

   MISSING_DATA                                           POLYLINE  
0         False  [[-8.585676,41.148522],[-8.585712,41.148639],[...  
1         False  [[-8.610876,41.14557],[-8.610858,41.145579],[-...  
2         False  [[-8.585739,41.148558],[-8.58573,41.148828],[-...  
3         False  [[-8.613963,41.141169],[-8.614125,41.141124],[...  
4         False      [[-8.619903,41.148036],[-8.619894,41.148036]]

In [54]:
meta = pd.read_csv("metaData_taxistandsID_name_GPSlocation.csv")

In [55]:
meta.head()

ID  Descricao       Latitude  Longitude
0   1       Agra  41.1771457135  -8.609670
1   2    Alameda    41.15618964  -8.591064
2   3     Aldoar  41.1705249231  -8.665876
3   4  Alfândega  41.1437639911  -8.621803
4   5      Amial  41.1835097223  -8.612726

In [56]:
meta.shape, test.shape, train.shape

((63, 4), (320, 9), (1710670, 9))

Ok. So we have 1.7 million training rides and only 320 test rides. Metadata is just having name of cities for lat/long. 

In [57]:
train.dtypes

TRIP_ID           int64
CALL_TYPE        object
ORIGIN_CALL     float64
ORIGIN_STAND    float64
TAXI_ID           int64
TIMESTAMP         int64
DAY_TYPE         object
MISSING_DATA       bool
POLYLINE         object
dtype: object

### Step 1. Feature extraction

Winner's process to convert csv to hdf5 and extract features. I would prefer working on `pandas` for the same as it will allow me to look at how data looks. Replicating all steps present in `csv_to_hdf5.py` to make pandas df

In [58]:
train2 = train.copy()
test2 = test.copy()
meta2 = meta.copy()

Below code proves that all the taxi ids in test set are also present in training set. We don't have any new taxi id in test data. But there are **20 origin calls** that are not in training data but are in test data. 

In [6]:
s=0
for l in test.TAXI_ID.unique():
    if l not in train.TAXI_ID.unique():
        s = s+1
p=0
g = []
for l in test.ORIGIN_CALL.unique():
    if l not in train.ORIGIN_CALL.unique():
        p = p+1
        g.append(l)
s,p

`g` as saved above has list of origin_calls that are in test but not in train

In [62]:
g[1:]

[85698.0,
 85224.0,
 86098.0,
 86436.0,
 74478.0,
 81753.0,
 67507.0,
 65127.0,
 66996.0,
 72185.0,
 75460.0,
 73870.0,
 72911.0,
 73071.0,
 75037.0,
 80148.0,
 66812.0,
 70885.0,
 76232.0]

Let's see how many unique `origin_calls` and `taxi_ids` do we have in both training and test set

In [63]:
len(train.TAXI_ID.unique()), len(test.TAXI_ID.unique()), len(train.ORIGIN_CALL.unique()), len(test.ORIGIN_CALL.unique())

(448, 244, 57106, 61)

So basically, approximately half of `taxi_ids` from training are there in test data.

Pre-calculated below on train set


In [5]:
lat_mean = 41.15731
lat_std = 0.074120656
long_mean = -8.6161413
long_std = 0.057200309

Making a new feature with only first 5 and last 5 coordinates. In cases where we don't have enough coordinates, we do `edge` padding (i.e. just adding first and last values in leftmost and rightmost sides respectively)

In [70]:
def start_stop_inputs(k, train, test):
    
    """
    Function used to take first k and last k coordinates from given polyline.
    For train - if total coordinates < 2 then return none, if > 2*k then return first k and last k
    and if > 2 but < 2*k then do edge padding and return.
    
    """
    result_train = []
    result_test = []
    
    for l in train[['LONGITUDE','LATITUDE']].iterrows():
        if len(l[1][0]) < 2 or len(l[1][1]) < 2:
            result_train.append(np.nan)
        elif len(l[1][0][:-1]) >= 2*k:
            result_train.append(np.concatenate([l[1][0][0:k],l[1][0][-k:],
                                          l[1][1][0:k],l[1][1][-k:]]).flatten())
        else:
            l1 = np.lib.pad(l[1][0][:-1], (0,4*k-len(l[1][0][:-1])), mode='edge')
            l2 = np.lib.pad(l[1][1][:-1], (0,4*k-len(l[1][1][:-1])), mode='edge')
            result_train.append(np.concatenate([l1[0:k],l1[-k:],l2[0:k],l2[-k:]]).flatten())

    for l in test[['LONGITUDE','LATITUDE']].iterrows(): 
        if len(l[1][0]) < 1 or len(l[1][1]) < 1:
            result_test.append(np.nan)
        elif len(l[1][0]) >= 2*k:
            result_test.append(np.concatenate([l[1][0][0:k],l[1][0][-k:],l[1][1][0:k],l[1][1][-k:]]).flatten())
        else:
            l1 = np.lib.pad(l[1][0], (0,4*k-len(l[1][0])), mode='edge')
            l2 = np.lib.pad(l[1][1], (0,4*k-len(l[1][1])), mode='edge')
            result_test.append(np.concatenate([l1[0:k],l1[-k:],l2[0:k],l2[-k:]]).flatten())
    
    return pd.Series(result_train), pd.Series(result_test)

In [75]:
import ast
def feature_ext(train, test):   
    """
    Function used to extract model features.
    • extract lat/long from polyline
    • lat/long normalized using pre-calculated mean and std
    • origin_call and taxi_id converted to continuous numbers (0 to ...) to get embeddings later
    • categories convert to cat codes
    
    """
    
    # origin_call -- train
    train.ORIGIN_CALL.fillna(value = -1, inplace=True)
    id_uniq = train.ORIGIN_CALL.unique()
    
    origin_call_dict = {o:i for i,o in enumerate(id_uniq)}

    train['ORIGIN_CALL'] = train.ORIGIN_CALL.apply(lambda x: 0 if x == -1 
                                                   or x == '' else origin_call_dict[x])
    
    
    # origin_call --test (g list of ids in test not in train)
    test.ORIGIN_CALL.fillna(value = -1, inplace=True)

    test['ORIGIN_CALL'] = test.ORIGIN_CALL.apply(lambda x: 0 if x == -1 or x == '' 
                                              else (-2 if x in g[1:] else origin_call_dict[x]))
    
    
    # origin_stand
    train['ORIGIN_STAND']= pd.Series([0 if pd.isnull(x) or x=='' else int(x) for x in train["ORIGIN_STAND"]])
    test['ORIGIN_STAND']= pd.Series([0 if pd.isnull(x) or x=='' else int(x) for x in test["ORIGIN_STAND"]])
    
    # taxi_id
    id_uniq = train.TAXI_ID.unique()
    taxi_id_dict = {o:i for i,o in enumerate(id_uniq)}
    train['TAXI_ID'] = train.TAXI_ID.apply(lambda x: taxi_id_dict[x])
    test['TAXI_ID'] = test.TAXI_ID.apply(lambda x: taxi_id_dict[x])

    # day_type and call_type
    # want 0 for A, 1 for B and 2 for C
    train['DAY_TYPE'] = pd.Series([ord(x[0]) - ord('A') for x in train['DAY_TYPE']])
    train['CALL_TYPE'] = pd.Series([ord(x[0]) - ord('A') for x in train['CALL_TYPE']])
    test['DAY_TYPE'] = pd.Series([ord(x[0]) - ord('A') for x in test['DAY_TYPE']])
    test['CALL_TYPE'] = pd.Series([ord(x[0]) - ord('A') for x in test['CALL_TYPE']])
    
    
    # polyline
    polyline1 = pd.Series([ast.literal_eval(x) for x in train['POLYLINE']])
    polyline2 = pd.Series([ast.literal_eval(x) for x in test['POLYLINE']])
    
    # latitude and longitude
    train['LATITUDE'] = pd.Series([np.array([point[1] for point in poly],dtype=np.float32) for poly in polyline1])
    train['LONGITUDE'] = pd.Series([np.array([point[0] for point in poly],dtype=np.float32) for poly in polyline1])
    
    test['LATITUDE'] = pd.Series([np.array([point[1] for point in poly],dtype=np.float32) for poly in polyline2])
    test['LONGITUDE'] = pd.Series([np.array([point[0] for point in poly],dtype=np.float32) for poly in polyline2])
    
    # target variable i.e. last coordinates
    train['TARGET'] = pd.Series([[l[1][0][-1], l[1][1][-1]] if len(l[1][0]) > 1 
                                else np.nan for l in train[['LONGITUDE','LATITUDE']].iterrows()])

    # normalized lat long. We need normalized data for neural nets and this is like cont. variable (not cat)
    train['LATITUDE'] = pd.Series([(t-lat_mean)/lat_std for t in train['LATITUDE']])
    test['LATITUDE'] = pd.Series([(t-lat_mean)/lat_std for t in test['LATITUDE']])
    
    train['LONGITUDE'] = pd.Series([(t-long_mean)/long_std for t in train['LONGITUDE']])
    test['LONGITUDE'] = pd.Series([(t-long_mean)/long_std for t in test['LONGITUDE']])

    # first 5 and last 5 features
    train['COORD_FEATURES'], test['COORD_FEATURES'] = start_stop_inputs(5, train, test)
    
    # day of week variable
    train['DAY_OF_WEEK'] = pd.Series([datetime.datetime.fromtimestamp(t).weekday() for t in train['TIMESTAMP']])
    test['DAY_OF_WEEK'] = pd.Series([datetime.datetime.fromtimestamp(t).weekday() for t in test['TIMESTAMP']])

    # hour of day
    train['HOUR'] = pd.Series([datetime.datetime.fromtimestamp(t).hour for t in train['TIMESTAMP']])
    test['HOUR'] = pd.Series([datetime.datetime.fromtimestamp(t).hour for t in test['TIMESTAMP']])

    # week of year
    train['WEEK_OF_YEAR'] = pd.Series([datetime.datetime.fromtimestamp(t).isocalendar()[1] for t in train['TIMESTAMP']])
    test['WEEK_OF_YEAR'] = pd.Series([datetime.datetime.fromtimestamp(t).isocalendar()[1] for t in test['TIMESTAMP']])

        
    #data = data.dropna()

    return train, test

In [77]:
train2, test2 = train.copy(), test.copy()

In [ ]:
train2, test2 = feature_ext(train2, test2)

In [9]:
train2[:2]

TRIP_ID  CALL_TYPE  ORIGIN_CALL  ORIGIN_STAND  TAXI_ID  \
0  1372636858620000589          2            0             0        0   
1  1372637303620000596          1            0             7        1   

    TIMESTAMP  DAY_TYPE  MISSING_DATA  \
0  1372636858         0         False   
1  1372637303         0         False   

                                            POLYLINE  \
0  [[-8.618643,41.141412],[-8.618499,41.141376],[...   
1  [[-8.639847,41.159826],[-8.640351,41.159871],[...   

                                            LATITUDE  \
0  [-0.21451, -0.214974, -0.199688, -0.182087, -0...   
1  [0.0339161, 0.0345337, 0.0378275, 0.0429227, 0...   

                                           LONGITUDE               TARGET  \
0  [-0.0437321, -0.0412145, -0.0731591, -0.105104...  [-8.63084, 41.1545]   
1  [-0.414429, -0.423249, -0.455494, -0.494991, -...  [-8.66574, 41.1707]   

                                      COORD_FEATURES  DAY_OF_WEEK  HOUR  \
0  [-0.0437321, -0.0412145, -0.0731591, -0.105104...            0     0   
1  [-0.414429, -0.423249, -0.455494, -0.494991, -...            0     0   

   WEEK_OF_YEAR  
0            27  
1            27

In [8]:
test2[:2]

TRIP_ID  CALL_TYPE  ORIGIN_CALL  ORIGIN_STAND  TAXI_ID   TIMESTAMP  \
0      T1          1            0            15      150  1408039037   
1      T2          1            0            57      306  1408038611   

   DAY_TYPE  MISSING_DATA                                           POLYLINE  \
0         0         False  [[-8.585676,41.148522],[-8.585712,41.148639],[...   
1         0         False  [[-8.610876,41.14557],[-8.610858,41.145579],[-...   

                                            LATITUDE  \
0  [-0.118578, -0.116982, -0.1141, -0.113122, -0....   
1  [-0.158413, -0.158258, -0.155736, -0.150024, -...   

                                           LONGITUDE  \
0  [0.532604, 0.531971, 0.532454, 0.531671, 0.527...   
1  [0.0920491, 0.0923659, 0.0915823, 0.0996017, 0...   

                                      COORD_FEATURES  DAY_OF_WEEK  HOUR  \
0  [0.532604, 0.531971, 0.532454, 0.531671, 0.527...            3    17   
1  [0.0920491, 0.0923659, 0.0915823, 0.0996017, 0...            3    17   

   WEEK_OF_YEAR  
0            33  
1            33

Saving transformed files as `pickle`

Saving files

In [101]:
train2.to_pickle(path+'train2pickle')
test2.to_pickle(path+'test2pickle')

Loading train and test. **Can directly run this**

In [6]:
train2 = pd.read_pickle('train2pickle')
test2 = pd.read_pickle('test2pickle')

After running `fit`, I got to know that we can not make predictions for **embeddings = -2** as it is not being trained. So there are only **20** such records, I am changing those as **0** in test set

In [7]:
test2.ORIGIN_CALL = test2.ORIGIN_CALL.apply(lambda x: 0 if x == -2 else x)

### Step 2: Meanshift clustering

** From the paper**

As the destination we aim to predict is composed of two scalar values (latitude and longitude), it is natural to have two output neurons. However, we found that it was difficult to train such a simple model because it does not take into account any prior information on the distribution of the data. To tackle this issue, we integrate prior knowledge of the destinations directly in the architecture of our model: instead of predicting directly the destination position, we use a predefined set (ci)1≤i≤C of a few thousand destination cluster centers and a hidden layer
that associates a scalar value (pi)i (similar to a probability) to each of these clusters. As the network must output a single destination position, for our output prediction yˆ, we compute a weighted average of the predefined destination cluster centers:

In [9]:
import os
from sklearn.cluster import MeanShift, estimate_bandwidth
from sklearn.datasets.samples_generator import make_blobs
from itertools import cycle
import scipy.misc

In [8]:
# checking how to index and subset lat and long (lat is in 1 and long in 0th)
train2.TARGET[:10][1][1], train2.TARGET[:10][1][0]

(41.17067, -8.66574)

We don't have polyline data for all the training data. For those, we have `nan` in `TARGET` variable and those won't contribute in centroid calculation. 

In [40]:
print("Generating arrival point list")
dests = []

# for l in train2[['LONGITUDE','LATITUDE']].iterrows():
#     if len(l[1][0]) == 0 or len(l[1][1]) == 0: continue
#     dests.append((l[1][1][-1],  l[1][0][-1])) # latitude, longitude

target = train2.TARGET.fillna(0)    
for l in target:
    if l == 0 : continue
    dests.append((l[1],  l[0])) # latitude, longitude
    
pts = np.array(dests)

with open(os.path.join(path, "arrivals.pkl"), "wb") as f:
    pickle.dump(pts, f, protocol=pickle.HIGHEST_PROTOCOL)

print("Doing clustering")
bw = estimate_bandwidth(pts, quantile=.1, n_samples=1000)
print(bw)
bw = 0.001 

ms = MeanShift(bandwidth=bw, bin_seeding=True, min_bin_freq=5)
ms.fit(pts)
cluster_centers = ms.cluster_centers_

print("Clusters shape: ", cluster_centers.shape)

with open(os.path.join(path, "arrival-clusters.pkl"), "wb") as f:
    pickle.dump(cluster_centers, f, protocol=pickle.HIGHEST_PROTOCOL)

Generating arrival point list
Doing clustering
0.0215466177411
Clusters shape:  (3422, 2)


I tried above code for --  
1. scaled coordinates. It doesn't give even close number of clusters. got **22644 clusters**. Not quite right. 
2. unscaled coordinates. Got **3422 clusters**. Winner had 3392 clusters. CLOSE and will keep it

### Step 3: Making Validation Split

As given in winner's solution, we are taking validation set as last year's data with same timestamp as of test data timestamps

In [10]:
# Cuts of the test set minus 1 year
cuts = [
    1376503200, # 2013-08-14 18:00
    1380616200, # 2013-10-01 08:30
    1381167900, # 2013-10-07 17:45
    1383364800, # 2013-11-02 04:00
    1387722600  # 2013-12-22 14:30
]

In [11]:
val_indices = []
index = 0
for index, row in train2.iterrows():
    time = row['TIMESTAMP']
    latitude = row['LATITUDE']
    for ts in cuts:
        if time <= ts and time + 15 * (len(latitude) - 1) >= ts:
            val_indices.append(index)
            break
    index += 1

saving and reloading validation indexes

In [23]:
with open(os.path.join(path, "val_idx.pkl"), "wb") as f:
    pickle.dump(val_indices, f)

In [12]:
with open(os.path.join(path, "val_idx.pkl"), "rb") as f:
    val_indices = pickle.load(f)

validation set

For making embedding layers, I will be needing indexes to feed as values. It will be used for doing lookup.

Before making validation set, this is something I am doing after getting stuck with some error in `fit`. I noticed that for `WEEK_OF_YEAR` and for `ORIGIN_STAND`, the cat codes do no match with index. For these 2, I will replace values with indexes. This is an experiment which is unlikely to change anything. Just trying it out -- **NOPE DIDN'T HELP**. Commented below 3 chunks

In [16]:
for c in cat_vars:
    s =0
    for i, v in enumerate(train2[c].unique()):
        s += i != v
    print(s, c)

In [96]:
# def EmbeddingDataPreprocess(data, cats, inplace=True):
#     ### Each categorical column should have indices as values
#     ### Which will be looked up at embedding matrix and used in modeling
#     ### Make changes inplace
#     if inplace:
#         for c in cats:
#             data[c].replace({val: i for i, val in enumerate(data[c].unique())}, inplace=True)
#         return data
#     else:
#         data_copy = data.copy()
#         for c in cats:
#             data_copy[c].replace({val: i for i, val in enumerate(data_copy[c].unique())}, inplace=True)
#         return data_copy

In [97]:
# EmbeddingDataPreprocess(train2, ['ORIGIN_STAND', 'WEEK_OF_YEAR'], inplace=True)

In [98]:
# for c in cat_vars:
#     s =0
#     for i, v in enumerate(train2[c].unique()):
#         s += i != v
#     print(s, c)

**Index == values** now

Found that in below codes, index of embedding for `WEEK_OF_YEAR` starts from 1 and others from 0. I am going to change that to make it start from 0 because I guess it is the reason of `cude runtime error` that I am getting. Experiment!!


In [13]:
# making week of year from 0-51 from 1-52

train2.WEEK_OF_YEAR = train2.WEEK_OF_YEAR - 1

In [14]:
# transformation on test set
test2.WEEK_OF_YEAR = test2.WEEK_OF_YEAR - 1

In [15]:
X_valid = train2.iloc[val_indices]

Let's check if we have right timestamps in validation set or not

In [16]:
lt = []
for d in X_valid['TIMESTAMP']:
    lt.append(datetime.date.fromtimestamp(d))
    
set(lt)

{datetime.date(2013, 8, 14),
 datetime.date(2013, 10, 1),
 datetime.date(2013, 10, 7),
 datetime.date(2013, 11, 2),
 datetime.date(2013, 12, 22)}

Yup. above dates match with our dates of test set. Just 1 previous year

In [17]:
X_train = train2.drop(train2.index[[val_indices]])

In [18]:
len(X_valid), len(X_train)

(304, 1710366)

Validation set length is similar as test set length

In [19]:
with open(os.path.join(path, "arrival-clusters.pkl"), "rb") as f:
    cluster_centers2 = pickle.load(f)

In [20]:
len(cluster_centers2)

3422

Saving `X_train` and `X_valid`

In [21]:
X_train.to_pickle(path + 'X_train.pkl')
X_valid.to_pickle(path + 'X_valid.pkl')

Reading validation and training files. Next time can directly read from here

In [184]:
X_train = pd.read_pickle('X_train.pkl')
X_valid = pd.read_pickle('X_valid.pkl')

### Step 4: DL

Hidden layer is basically telling probability of observation being in ith cluster. So it will have as many outputs as number of clusters. (3422). It includes training for `probabilities`  

Now sum of all the `probabilities` should be 1. Therefore we will use `softmax` over a trained linear layer


On these 3422 output from hidden, we take weighted avg which will just be sum of multiplied probability into cluster center (i.e. sum of 3422 elements). It includes no traning, just using previous probabilities, multiplying by fixed crntroid coordinated and calculating weighted avg.   

Think of this operation as a linear layer with `weights = centers (i.e. fixed) and input = probabilities`



Layers to add:  
1. Pass input data to a **dense layer** which has 500 outputs and those **500 to relu**. 
1. Pass coming data to a **linear layer** which has 3422 outputs
2. These 3422 outputs passed to a **softmax** (which will give p)
3. These 3422 p's will go to **linear layer** which **does not** update weights.  just multiply p and c . 
4. 


#### Analysing cardinality for embeddings

In [22]:
cols = ['ORIGIN_CALL', 'TAXI_ID', 'ORIGIN_STAND', 'HOUR', 'DAY_OF_WEEK', 'WEEK_OF_YEAR']

In [23]:
for i in cols:
    print(i, '--', 'Possible values', len(train2[i].unique()) ,'||', 'Embedding size', 10)

ORIGIN_CALL -- Possible values 57106 || Embedding size 10
TAXI_ID -- Possible values 448 || Embedding size 10
ORIGIN_STAND -- Possible values 64 || Embedding size 10
HOUR -- Possible values 24 || Embedding size 10
DAY_OF_WEEK -- Possible values 7 || Embedding size 10
WEEK_OF_YEAR -- Possible values 52 || Embedding size 10


They took embedding of size 10 for all the above features

In [24]:
emb_szs = []
for i in cols:
    emb_szs.append((len(train2[i].unique()), 10))
emb_szs

[(57106, 10), (448, 10), (64, 10), (24, 10), (7, 10), (52, 10)]

In [25]:
cat_vars = ['ORIGIN_CALL', 'TAXI_ID', 'ORIGIN_STAND', 'HOUR', 'DAY_OF_WEEK', 'WEEK_OF_YEAR']
#cont_vars = 

#### Getting continuous features

In [26]:
X_train[:1]

TRIP_ID  CALL_TYPE  ORIGIN_CALL  ORIGIN_STAND  TAXI_ID  \
0  1372636858620000589          2            0             0        0   

    TIMESTAMP  DAY_TYPE  MISSING_DATA  \
0  1372636858         0         False   

                                            POLYLINE  \
0  [[-8.618643,41.141412],[-8.618499,41.141376],[...   

                                            LATITUDE  \
0  [-0.21451, -0.214974, -0.199688, -0.182087, -0...   

                                           LONGITUDE               TARGET  \
0  [-0.0437321, -0.0412145, -0.0731591, -0.105104...  [-8.63084, 41.1545]   

                                      COORD_FEATURES  DAY_OF_WEEK  HOUR  \
0  [-0.0437321, -0.0412145, -0.0731591, -0.105104...            0     0   

   WEEK_OF_YEAR  
0            26

In [26]:
import warnings
warnings.filterwarnings("ignore")

In [27]:
# replacing NA with 0s
# k = 5

X_train.COORD_FEATURES.fillna(0, inplace = True)
X_valid.COORD_FEATURES.fillna(0, inplace = True)

In [28]:
test2.COORD_FEATURES.fillna(0, inplace = True)

In [29]:
def get_features(df, target = True):
    
    cols = ['ORIGIN_CALL', 'TAXI_ID', 'ORIGIN_STAND', 'HOUR', 'DAY_OF_WEEK', 'WEEK_OF_YEAR','MISSING_DATA']
    
    df_feat = df[cols]
    for i in range(10):
        df_feat[f'long_{i}'] = df.COORD_FEATURES.apply(lambda x: 0 if type(x) == int else x[i]) # creating 10 cols for long
        df_feat[f'lat_{i}'] = df.COORD_FEATURES.apply(lambda x: 0 if type(x) == int else x[i+10]) # 10 cols for lat

    if target is True:
        df_target = df['TARGET']
    else:
        df_target = None
               
    return df_feat, df_target

Training and validation sets

In [30]:
train2.COORD_FEATURES.fillna(0, inplace = True)
df, y = get_features(train2)

In [31]:
train_feat, train_target = get_features(X_train)

In [32]:
valid_feat, valid_target = get_features(X_valid) 

In [33]:
test_feat, test_target = get_features(test2, target = False)

Centers of cluster lats and longs. Needed for last nn layer

In [34]:
cluster_lats = []

for i in cluster_centers2:
    cluster_lats.append(i[0])
    
cluster_longs = []

for i in cluster_centers2:
    cluster_longs.append(i[1])

In [35]:
cluster_lats = np.array(cluster_lats)[:,None]
cluster_longs = np.array(cluster_longs)[:,None]

Mixed input nn model

#### Data loader

Customizing `fast.ai` functions

#### After loading data into dataloader, writing my own training loop (tried `get_learner` from fastai. doesn't work for me)

In [36]:
class taxi_dataset_from_df():
    def __init__(self, df, cats, y):
        #n = len(cats[0]) if cats else len(conts[0])
        
        self.df_cats = df[cats]
        self.df_conts = df.drop(cats, axis=1)
        
        lat = y.fillna(0).apply(lambda x: 0 if type(x) == int else x[1])
        long = y.fillna(0).apply(lambda x: 0 if type(x) == int else x[0])
        
        target = pd.DataFrame({'long': long.astype(np.float32),'lat' : lat.astype(np.float32)})
        
        cat_cols = [c.values for n,c in self.df_cats.items()]
        cont_cols = [c.values for n,c in self.df_conts.items()]  
        target_cols = [c.values for n,c in target.items()]  
        
        self.cats = np.stack(cat_cols, 1).astype(np.int64)
        self.conts = np.stack(cont_cols, 1).astype(np.float32) 
        self.target = np.stack(target_cols, 1).astype(np.float32) 

    def __len__(self): return len(self.df_cats)

    def __getitem__(self, idx):
        return [self.cats[idx], self.conts[idx], self.target[idx]]


In [37]:
train_dataset = taxi_dataset_from_df(train_feat, cat_vars, train_target)

train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=200, shuffle=True)

In [38]:
valid_feat.shape

(304, 27)

In [39]:
valid_dataset = taxi_dataset_from_df(valid_feat, cat_vars, valid_target)

valid_loader = torch.utils.data.DataLoader(valid_dataset, batch_size=304, shuffle=False)

In [40]:
class taxi_dataset_from_df_test():
    def __init__(self, df, cats):
        #n = len(cats[0]) if cats else len(conts[0])
        
        self.df_cats = df[cats]
        self.df_conts = df.drop(cats, axis=1)
        
        #lat = y.fillna(0).apply(lambda x: 0 if type(x) == int else x[1])
        #long = y.fillna(0).apply(lambda x: 0 if type(x) == int else x[0])
        
        #target = pd.DataFrame({'long': long.astype(np.float32),'lat' : lat.astype(np.float32)})
        
        cat_cols = [c.values for n,c in self.df_cats.items()]
        cont_cols = [c.values for n,c in self.df_conts.items()]  
        #target_cols = [c.values for n,c in target.items()]  
        
        self.cats = np.stack(cat_cols, 1).astype(np.int64)
        self.conts = np.stack(cont_cols, 1).astype(np.float32) 
       # self.target = np.stack(target_cols, 1).astype(np.float32) 

    def __len__(self): return len(self.df_cats)

    def __getitem__(self, idx):
        return [self.cats[idx], self.conts[idx]]


In [41]:
test2.shape

(320, 15)

In [42]:
test_dataset = taxi_dataset_from_df_test(test_feat, cat_vars)

test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=320, shuffle=False)

let's see what my dataset is returning. It is a list with 3 elements. cat df, cont df and y.

**NOTICE that lat is in 0 here and long is in 1**

In [105]:
train_dataset[0:3]

[array([[ 0,  0,  0,  0,  0, 26],
        [ 0,  1,  7,  0,  0, 26],
        [ 0,  2,  0,  0,  0, 26]]),
 array([[ 0.     , -0.04373, -0.21451, -0.04121, -0.21497, -0.07316, -0.19969, -0.1051 , -0.18209, -0.13656,
         -0.17452, -0.26228, -0.03808, -0.25677, -0.03783, -0.25677, -0.03772, -0.25677, -0.03793, -0.25694,
         -0.03808],
        [ 0.     , -0.41443,  0.03392, -0.42325,  0.03453, -0.45549,  0.03783, -0.49499,  0.04292, -0.53811,
          0.0491 , -0.93476,  0.14369, -0.90834,  0.15754, -0.88284,  0.17128, -0.86757,  0.17977, -0.86711,
          0.18023],
        [ 0.     ,  0.05555, -0.22872,  0.04832, -0.22882,  0.03368, -0.2298 ,  0.02393, -0.22856,  0.0041 ,
         -0.22748, -0.13893, -0.17334, -0.09062, -0.18765, -0.05774, -0.2071 , -0.02139, -0.22192,  0.003  ,
         -0.2264 ]], dtype=float32),
 array([[ 41.15449,  -8.63084],
        [ 41.17067,  -8.66574],
        [ 41.14053,  -8.61597]], dtype=float32)]

In [106]:
train_dataset[:][0]

array([[  0,   0,   0,   0,   0,  26],
       [  0,   1,   7,   0,   0,  26],
       [  0,   2,   0,   0,   0,  26],
       ..., 
       [  0, 439,   0,  10,   4,   0],
       [  0, 443,  12,  15,   0,  26],
       [  0, 444,  34,  19,   0,  26]])

In [43]:
np.min(test_dataset[:][0], 0), np.max(test_dataset[:][0], 0)

(array([ 0,  0,  0,  2,  0, 32]),
 array([47093,   444,    63,    17,     6,    50]))

In [44]:
np.min(train_dataset[:][0], 0), np.max(train_dataset[:][0], 0)

(array([0, 0, 0, 0, 0, 0]), array([57105,   447,    63,    23,     6,    51]))

In [45]:
np.min(valid_dataset[:][0], 0), np.max(valid_dataset[:][0], 0)

(array([ 0,  0,  0,  3,  0, 32]),
 array([34587,   435,    63,    17,     6,    50]))

Ok. So let's think on how will I use input of these for in dataloader and that into my `Net`

#### Defining Loss function

They used `equirectangular distance` as loss function which performed better than original kaggle metric (`Haversine distance`). Actually equirectangular distance is just a simpler approximation to haversine distance

Will keep long in 0 and lat in 1 as there in target column

In [194]:
# a predicted, b true
# data loader is in such a way that true y should be indexed from floatTensor

class equiRectLoss(nn.Module):

    def __init__(self):
        super(equiRectLoss, self).__init__()
        self.rearth = 6371
        self.deg2rad = 3.141592653589793 / 180.

    def forward(self, a,b):  
        lat1 = a[:,0]
        lon1 = a[:,1]
        lat2 = b[:,0]
        lon2 = b[:,1]   
        
        x = (lon2-lon1) * torch.cos((lat1+lat2)/2)
        y = (lat2-lat1)

        loss = torch.mean((torch.sqrt(x**2 + y**2) * self.rearth),dim=0)
        return loss

#### defining nn

In [46]:
cluster_latsV = torch.Tensor(cluster_lats)
cluster_longsV = torch.Tensor(cluster_longs)
clus_latlong = torch.cat((cluster_latsV, cluster_longsV), dim=1)

In [47]:
clus_latlong.shape

torch.Size([3422, 2])

In [48]:
def emb_init(x):
    x = x.weight.data
    sc = 2/(x.size(1)+1)
    x.uniform_(-sc,sc)

In [49]:
def final_layer_wt(x):
    x = x.weight.data
    x = clus_latlong
    return x

In [50]:
# they didn't do batchnormm in paper            
class Net(nn.Module):
    def __init__(self, emb_szs, n_cont,
                 y_range=None, use_bn=False):
        super().__init__()
        
        self.embs = nn.ModuleList([nn.Embedding(c, s) for c,s in emb_szs])
        for emb in self.embs: emb_init(emb)
        #n_emb = sum(e.embedding_dim for e in self.embs)
        n_emb = 60
        
        # 6 cat vars . therefore 60 embeddings (10 each)
        self.lin1 = nn.Linear(n_emb + n_cont, 500) # 1st linear layer -- no. features x 500
        self.relu = nn.ReLU()   # 2nd relu layer (output = 500 neurons)
        self.lin2 = nn.Linear(500, 3422)  # 3rd linear layer. 500x3422
        self.soft = nn.Softmax() # 4th softmax layer. 3422 probabilities (will sum to 1)
         
        for o in [self.lin1, self.lin2] : kaiming_normal(o.weight.data) #weight initialization for lin layers
            
        self.bn = nn.BatchNorm1d(n_cont) 
        
        self.lin3 = nn.Linear(3422,2)
        
        for o in [self.lin3]: final_layer_wt(o)
        #for o in [self.lin3] : kaiming_normal(o.weight.data)

    def forward(self, x_cat, x_cont):
        x = [e(x_cat[:,i]) for i,e in enumerate(self.embs)]
        x = torch.cat(x, 1)
        x2 = self.bn(x_cont)
        x = torch.cat([x, x2], 1)
        
        out = self.lin1(x)
        out = self.relu(out)
        out = self.lin2(out)
        out = self.soft(out)
#         outlat = out.mm(cluster_latsV)  # out is n*3422 and cluster_lats is 3422*1
#         outlong = out.mm(cluster_longsV)
        out = self.lin3(out)
        
        #target = pd.DataFrame({'long': outlong.astype(np.float32),'lat' : outlat.astype(np.float32)})
        #target_cols = [c.values for n,c in target.items()]  
        #target_out = torch.cat((cluster_latsV, cluster_longsV), dim=1)

        return out # nx2 tensor where n is no. of observations

In [51]:
it = iter(train_loader)
a,b,c = next(it)

In [52]:
a.shape, b.shape, c.shape

(torch.Size([200, 6]), torch.Size([200, 21]), torch.Size([200, 2]))

In [53]:
def score(x, y):
    y_pred = to_np(net2(V(x)))
    return np.sum(y_pred.argmax(axis=1) == to_np(y))/len(y_pred)

In [55]:
net1 = Net(emb_szs= emb_szs, n_cont= len(df.columns)-len(cat_vars), y_range=y)
net1 = net1.cuda()
loss= F.mse_loss
learning_rate = 1e-2 # can try different values, cyclic and diff learning rates
#optimizer=optim.SGD(net2.parameters(), lr=learning_rate, momentum = 0.9)
optimizer=optim.Adam(net1.parameters(), lr=learning_rate) # will check if weight_decay needed or not later


for epoch in range(2):
    losses=[]
    losses_val = []
    running_loss = 0.0
    #running_loss_valid = 0.0
    examples = 0
    #dl = iter(train_loader)
    for i, data in enumerate(train_loader, 0):
    #for t in range(len(dl)):
        # Forward pass: compute predicted y and loss by passing x to the model.
        xcat, xcont, yt = data      
        y_pred = net1(V(xcat), V(xcont))
        l = loss(y_pred, V(yt))
        
#         xcat_val, xcont_val, yt_val = valid_dataset[:]
#         l_valid = loss(net1(V(T(xcat_val)), V(T(xcont_val))), V(T(yt_val)))
        
#         losses_val.append(l_valid)
        
        # Before the backward pass, use the optimizer object to zero all of the
        # gradients for the variables it will update (which are the learnable weights of the model)
        optimizer.zero_grad()

        # Backward pass: compute gradient of the loss with respect to model parameters
        l.backward()

        # Calling the step function on an Optimizer makes an update to its parameters
        optimizer.step()
        
        # Print statistics
        running_loss += l.data[0]
        #running_loss_valid += l_valid.data[0]
        examples += 10
        
        print('[%d, %5d] Training loss: %.3f' % (epoch + 1, i + 1, running_loss / examples))
        
        #print('[%d, %5d] Training loss: %.3f Validation loss: %.3f' % (epoch + 1, i + 1, running_loss / examples, 
                                                 # running_loss_valid/examples))
        
print('Finished Training')

[1,     1] Training loss: 87.158
[1,     2] Training loss: 85.766
[1,     3] Training loss: 85.712
[1,     4] Training loss: 85.437
[1,     5] Training loss: 85.691
[1,     6] Training loss: 85.552
[1,     7] Training loss: 85.500
[1,     8] Training loss: 85.557
[1,     9] Training loss: 85.496
[1,    10] Training loss: 85.699
[1,    11] Training loss: 85.698
[1,    12] Training loss: 85.763
[1,    13] Training loss: 85.676
[1,    14] Training loss: 85.594
[1,    15] Training loss: 85.575
[1,    16] Training loss: 85.553
[1,    17] Training loss: 85.502
[1,    18] Training loss: 85.475
[1,    19] Training loss: 85.446
[1,    20] Training loss: 85.437
[1,    21] Training loss: 85.342
[1,    22] Training loss: 85.350
[1,    23] Training loss: 85.222
[1,    24] Training loss: 85.225
[1,    25] Training loss: 85.191
[1,    26] Training loss: 85.122
[1,    27] Training loss: 85.054
[1,    28] Training loss: 84.988
[1,    29] Training loss: 84.953
[1,    30] Training loss: 84.931
[1,    31]

[1,   253] Training loss: 74.489
[1,   254] Training loss: 74.441
[1,   255] Training loss: 74.400
[1,   256] Training loss: 74.360
[1,   257] Training loss: 74.323
[1,   258] Training loss: 74.282
[1,   259] Training loss: 74.241
[1,   260] Training loss: 74.197
[1,   261] Training loss: 74.156
[1,   262] Training loss: 74.113
[1,   263] Training loss: 74.072
[1,   264] Training loss: 74.033
[1,   265] Training loss: 73.991
[1,   266] Training loss: 73.948
[1,   267] Training loss: 73.909
[1,   268] Training loss: 73.870
[1,   269] Training loss: 73.825
[1,   270] Training loss: 73.784
[1,   271] Training loss: 73.744
[1,   272] Training loss: 73.699
[1,   273] Training loss: 73.659
[1,   274] Training loss: 73.620
[1,   275] Training loss: 73.581
[1,   276] Training loss: 73.538
[1,   277] Training loss: 73.496
[1,   278] Training loss: 73.459
[1,   279] Training loss: 73.421
[1,   280] Training loss: 73.382
[1,   281] Training loss: 73.339
[1,   282] Training loss: 73.297
[1,   283]

[1,   517] Training loss: 64.683
[1,   518] Training loss: 64.649
[1,   519] Training loss: 64.616
[1,   520] Training loss: 64.582
[1,   521] Training loss: 64.550
[1,   522] Training loss: 64.516
[1,   523] Training loss: 64.483
[1,   524] Training loss: 64.450
[1,   525] Training loss: 64.417
[1,   526] Training loss: 64.383
[1,   527] Training loss: 64.349
[1,   528] Training loss: 64.314
[1,   529] Training loss: 64.281
[1,   530] Training loss: 64.249
[1,   531] Training loss: 64.216
[1,   532] Training loss: 64.184
[1,   533] Training loss: 64.150
[1,   534] Training loss: 64.117
[1,   535] Training loss: 64.084
[1,   536] Training loss: 64.051
[1,   537] Training loss: 64.017
[1,   538] Training loss: 63.984
[1,   539] Training loss: 63.950
[1,   540] Training loss: 63.917
[1,   541] Training loss: 63.885
[1,   542] Training loss: 63.852
[1,   543] Training loss: 63.818
[1,   544] Training loss: 63.785
[1,   545] Training loss: 63.753
[1,   546] Training loss: 63.720
[1,   547]

[1,   781] Training loss: 56.620
[1,   782] Training loss: 56.592
[1,   783] Training loss: 56.564
[1,   784] Training loss: 56.536
[1,   785] Training loss: 56.508
[1,   786] Training loss: 56.480
[1,   787] Training loss: 56.452
[1,   788] Training loss: 56.425
[1,   789] Training loss: 56.397
[1,   790] Training loss: 56.370
[1,   791] Training loss: 56.342
[1,   792] Training loss: 56.315
[1,   793] Training loss: 56.287
[1,   794] Training loss: 56.259
[1,   795] Training loss: 56.231
[1,   796] Training loss: 56.204
[1,   797] Training loss: 56.176
[1,   798] Training loss: 56.148
[1,   799] Training loss: 56.120
[1,   800] Training loss: 56.093
[1,   801] Training loss: 56.066
[1,   802] Training loss: 56.038
[1,   803] Training loss: 56.011
[1,   804] Training loss: 55.983
[1,   805] Training loss: 55.955
[1,   806] Training loss: 55.927
[1,   807] Training loss: 55.900
[1,   808] Training loss: 55.872
[1,   809] Training loss: 55.845
[1,   810] Training loss: 55.817
[1,   811]

[1,  1045] Training loss: 49.826
[1,  1046] Training loss: 49.802
[1,  1047] Training loss: 49.778
[1,  1048] Training loss: 49.754
[1,  1049] Training loss: 49.731
[1,  1050] Training loss: 49.707
[1,  1051] Training loss: 49.683
[1,  1052] Training loss: 49.660
[1,  1053] Training loss: 49.636
[1,  1054] Training loss: 49.613
[1,  1055] Training loss: 49.589
[1,  1056] Training loss: 49.566
[1,  1057] Training loss: 49.542
[1,  1058] Training loss: 49.519
[1,  1059] Training loss: 49.495
[1,  1060] Training loss: 49.472
[1,  1061] Training loss: 49.448
[1,  1062] Training loss: 49.425
[1,  1063] Training loss: 49.401
[1,  1064] Training loss: 49.378
[1,  1065] Training loss: 49.354
[1,  1066] Training loss: 49.331
[1,  1067] Training loss: 49.308
[1,  1068] Training loss: 49.284
[1,  1069] Training loss: 49.261
[1,  1070] Training loss: 49.238
[1,  1071] Training loss: 49.214
[1,  1072] Training loss: 49.191
[1,  1073] Training loss: 49.168
[1,  1074] Training loss: 49.144
[1,  1075]

[1,  1309] Training loss: 44.049
[1,  1310] Training loss: 44.028
[1,  1311] Training loss: 44.008
[1,  1312] Training loss: 43.988
[1,  1313] Training loss: 43.968
[1,  1314] Training loss: 43.948
[1,  1315] Training loss: 43.928
[1,  1316] Training loss: 43.908
[1,  1317] Training loss: 43.888
[1,  1318] Training loss: 43.868
[1,  1319] Training loss: 43.848
[1,  1320] Training loss: 43.828
[1,  1321] Training loss: 43.808
[1,  1322] Training loss: 43.788
[1,  1323] Training loss: 43.768
[1,  1324] Training loss: 43.748
[1,  1325] Training loss: 43.728
[1,  1326] Training loss: 43.708
[1,  1327] Training loss: 43.688
[1,  1328] Training loss: 43.668
[1,  1329] Training loss: 43.648
[1,  1330] Training loss: 43.628
[1,  1331] Training loss: 43.608
[1,  1332] Training loss: 43.588
[1,  1333] Training loss: 43.569
[1,  1334] Training loss: 43.549
[1,  1335] Training loss: 43.529
[1,  1336] Training loss: 43.510
[1,  1337] Training loss: 43.490
[1,  1338] Training loss: 43.470
[1,  1339]

[1,  1573] Training loss: 39.137
[1,  1574] Training loss: 39.120
[1,  1575] Training loss: 39.103
[1,  1576] Training loss: 39.086
[1,  1577] Training loss: 39.069
[1,  1578] Training loss: 39.052
[1,  1579] Training loss: 39.035
[1,  1580] Training loss: 39.018
[1,  1581] Training loss: 39.001
[1,  1582] Training loss: 38.983
[1,  1583] Training loss: 38.966
[1,  1584] Training loss: 38.949
[1,  1585] Training loss: 38.933
[1,  1586] Training loss: 38.916
[1,  1587] Training loss: 38.899
[1,  1588] Training loss: 38.882
[1,  1589] Training loss: 38.864
[1,  1590] Training loss: 38.848
[1,  1591] Training loss: 38.831
[1,  1592] Training loss: 38.814
[1,  1593] Training loss: 38.797
[1,  1594] Training loss: 38.780
[1,  1595] Training loss: 38.763
[1,  1596] Training loss: 38.746
[1,  1597] Training loss: 38.729
[1,  1598] Training loss: 38.712
[1,  1599] Training loss: 38.696
[1,  1600] Training loss: 38.679
[1,  1601] Training loss: 38.662
[1,  1602] Training loss: 38.645
[1,  1603]

[1,  1831] Training loss: 35.056
[1,  1832] Training loss: 35.042
[1,  1833] Training loss: 35.027
[1,  1834] Training loss: 35.012
[1,  1835] Training loss: 34.998
[1,  1836] Training loss: 34.983
[1,  1837] Training loss: 34.968
[1,  1838] Training loss: 34.954
[1,  1839] Training loss: 34.939
[1,  1840] Training loss: 34.925
[1,  1841] Training loss: 34.910
[1,  1842] Training loss: 34.896
[1,  1843] Training loss: 34.881
[1,  1844] Training loss: 34.867
[1,  1845] Training loss: 34.853
[1,  1846] Training loss: 34.838
[1,  1847] Training loss: 34.823
[1,  1848] Training loss: 34.809
[1,  1849] Training loss: 34.794
[1,  1850] Training loss: 34.780
[1,  1851] Training loss: 34.766
[1,  1852] Training loss: 34.751
[1,  1853] Training loss: 34.737
[1,  1854] Training loss: 34.723
[1,  1855] Training loss: 34.708
[1,  1856] Training loss: 34.694
[1,  1857] Training loss: 34.680
[1,  1858] Training loss: 34.666
[1,  1859] Training loss: 34.651
[1,  1860] Training loss: 34.637
[1,  1861]

[1,  2095] Training loss: 31.511
[1,  2096] Training loss: 31.499
[1,  2097] Training loss: 31.487
[1,  2098] Training loss: 31.475
[1,  2099] Training loss: 31.462
[1,  2100] Training loss: 31.450
[1,  2101] Training loss: 31.438
[1,  2102] Training loss: 31.426
[1,  2103] Training loss: 31.414
[1,  2104] Training loss: 31.401
[1,  2105] Training loss: 31.389
[1,  2106] Training loss: 31.376
[1,  2107] Training loss: 31.365
[1,  2108] Training loss: 31.353
[1,  2109] Training loss: 31.341
[1,  2110] Training loss: 31.328
[1,  2111] Training loss: 31.316
[1,  2112] Training loss: 31.304
[1,  2113] Training loss: 31.292
[1,  2114] Training loss: 31.279
[1,  2115] Training loss: 31.267
[1,  2116] Training loss: 31.255
[1,  2117] Training loss: 31.242
[1,  2118] Training loss: 31.230
[1,  2119] Training loss: 31.218
[1,  2120] Training loss: 31.206
[1,  2121] Training loss: 31.194
[1,  2122] Training loss: 31.182
[1,  2123] Training loss: 31.170
[1,  2124] Training loss: 31.157
[1,  2125]

[1,  2359] Training loss: 28.513
[1,  2360] Training loss: 28.502
[1,  2361] Training loss: 28.492
[1,  2362] Training loss: 28.481
[1,  2363] Training loss: 28.471
[1,  2364] Training loss: 28.460
[1,  2365] Training loss: 28.450
[1,  2366] Training loss: 28.440
[1,  2367] Training loss: 28.429
[1,  2368] Training loss: 28.419
[1,  2369] Training loss: 28.408
[1,  2370] Training loss: 28.398
[1,  2371] Training loss: 28.388
[1,  2372] Training loss: 28.377
[1,  2373] Training loss: 28.367
[1,  2374] Training loss: 28.356
[1,  2375] Training loss: 28.347
[1,  2376] Training loss: 28.336
[1,  2377] Training loss: 28.326
[1,  2378] Training loss: 28.316
[1,  2379] Training loss: 28.305
[1,  2380] Training loss: 28.295
[1,  2381] Training loss: 28.284
[1,  2382] Training loss: 28.274
[1,  2383] Training loss: 28.263
[1,  2384] Training loss: 28.253
[1,  2385] Training loss: 28.243
[1,  2386] Training loss: 28.232
[1,  2387] Training loss: 28.222
[1,  2388] Training loss: 28.212
[1,  2389]

[1,  2623] Training loss: 25.983
[1,  2624] Training loss: 25.975
[1,  2625] Training loss: 25.966
[1,  2626] Training loss: 25.957
[1,  2627] Training loss: 25.948
[1,  2628] Training loss: 25.939
[1,  2629] Training loss: 25.930
[1,  2630] Training loss: 25.922
[1,  2631] Training loss: 25.913
[1,  2632] Training loss: 25.904
[1,  2633] Training loss: 25.895
[1,  2634] Training loss: 25.886
[1,  2635] Training loss: 25.877
[1,  2636] Training loss: 25.869
[1,  2637] Training loss: 25.860
[1,  2638] Training loss: 25.851
[1,  2639] Training loss: 25.843
[1,  2640] Training loss: 25.834
[1,  2641] Training loss: 25.825
[1,  2642] Training loss: 25.816
[1,  2643] Training loss: 25.807
[1,  2644] Training loss: 25.799
[1,  2645] Training loss: 25.790
[1,  2646] Training loss: 25.782
[1,  2647] Training loss: 25.773
[1,  2648] Training loss: 25.765
[1,  2649] Training loss: 25.756
[1,  2650] Training loss: 25.748
[1,  2651] Training loss: 25.739
[1,  2652] Training loss: 25.731
[1,  2653]

[1,  2886] Training loss: 23.852
[1,  2887] Training loss: 23.846
[1,  2888] Training loss: 23.838
[1,  2889] Training loss: 23.831
[1,  2890] Training loss: 23.824
[1,  2891] Training loss: 23.816
[1,  2892] Training loss: 23.808
[1,  2893] Training loss: 23.801
[1,  2894] Training loss: 23.793
[1,  2895] Training loss: 23.786
[1,  2896] Training loss: 23.778
[1,  2897] Training loss: 23.771
[1,  2898] Training loss: 23.764
[1,  2899] Training loss: 23.756
[1,  2900] Training loss: 23.749
[1,  2901] Training loss: 23.741
[1,  2902] Training loss: 23.733
[1,  2903] Training loss: 23.726
[1,  2904] Training loss: 23.719
[1,  2905] Training loss: 23.712
[1,  2906] Training loss: 23.705
[1,  2907] Training loss: 23.697
[1,  2908] Training loss: 23.689
[1,  2909] Training loss: 23.682
[1,  2910] Training loss: 23.674
[1,  2911] Training loss: 23.667
[1,  2912] Training loss: 23.660
[1,  2913] Training loss: 23.652
[1,  2914] Training loss: 23.645
[1,  2915] Training loss: 23.638
[1,  2916]

[1,  3150] Training loss: 22.035
[1,  3151] Training loss: 22.029
[1,  3152] Training loss: 22.023
[1,  3153] Training loss: 22.016
[1,  3154] Training loss: 22.010
[1,  3155] Training loss: 22.003
[1,  3156] Training loss: 21.997
[1,  3157] Training loss: 21.991
[1,  3158] Training loss: 21.985
[1,  3159] Training loss: 21.978
[1,  3160] Training loss: 21.972
[1,  3161] Training loss: 21.965
[1,  3162] Training loss: 21.959
[1,  3163] Training loss: 21.952
[1,  3164] Training loss: 21.946
[1,  3165] Training loss: 21.939
[1,  3166] Training loss: 21.932
[1,  3167] Training loss: 21.926
[1,  3168] Training loss: 21.920
[1,  3169] Training loss: 21.914
[1,  3170] Training loss: 21.907
[1,  3171] Training loss: 21.901
[1,  3172] Training loss: 21.894
[1,  3173] Training loss: 21.888
[1,  3174] Training loss: 21.882
[1,  3175] Training loss: 21.876
[1,  3176] Training loss: 21.870
[1,  3177] Training loss: 21.863
[1,  3178] Training loss: 21.857
[1,  3179] Training loss: 21.851
[1,  3180]

[1,  3414] Training loss: 20.485
[1,  3415] Training loss: 20.480
[1,  3416] Training loss: 20.474
[1,  3417] Training loss: 20.468
[1,  3418] Training loss: 20.463
[1,  3419] Training loss: 20.458
[1,  3420] Training loss: 20.453
[1,  3421] Training loss: 20.447
[1,  3422] Training loss: 20.442
[1,  3423] Training loss: 20.436
[1,  3424] Training loss: 20.431
[1,  3425] Training loss: 20.425
[1,  3426] Training loss: 20.420
[1,  3427] Training loss: 20.415
[1,  3428] Training loss: 20.410
[1,  3429] Training loss: 20.404
[1,  3430] Training loss: 20.398
[1,  3431] Training loss: 20.393
[1,  3432] Training loss: 20.388
[1,  3433] Training loss: 20.382
[1,  3434] Training loss: 20.377
[1,  3435] Training loss: 20.371
[1,  3436] Training loss: 20.365
[1,  3437] Training loss: 20.361
[1,  3438] Training loss: 20.356
[1,  3439] Training loss: 20.350
[1,  3440] Training loss: 20.345
[1,  3441] Training loss: 20.339
[1,  3442] Training loss: 20.334
[1,  3443] Training loss: 20.329
[1,  3444]

[1,  3680] Training loss: 19.141
[1,  3681] Training loss: 19.136
[1,  3682] Training loss: 19.131
[1,  3683] Training loss: 19.127
[1,  3684] Training loss: 19.122
[1,  3685] Training loss: 19.118
[1,  3686] Training loss: 19.113
[1,  3687] Training loss: 19.108
[1,  3688] Training loss: 19.103
[1,  3689] Training loss: 19.099
[1,  3690] Training loss: 19.094
[1,  3691] Training loss: 19.090
[1,  3692] Training loss: 19.085
[1,  3693] Training loss: 19.081
[1,  3694] Training loss: 19.077
[1,  3695] Training loss: 19.072
[1,  3696] Training loss: 19.068
[1,  3697] Training loss: 19.063
[1,  3698] Training loss: 19.059
[1,  3699] Training loss: 19.054
[1,  3700] Training loss: 19.049
[1,  3701] Training loss: 19.045
[1,  3702] Training loss: 19.040
[1,  3703] Training loss: 19.035
[1,  3704] Training loss: 19.030
[1,  3705] Training loss: 19.026
[1,  3706] Training loss: 19.021
[1,  3707] Training loss: 19.017
[1,  3708] Training loss: 19.012
[1,  3709] Training loss: 19.007
[1,  3710]

[1,  3944] Training loss: 17.986
[1,  3945] Training loss: 17.982
[1,  3946] Training loss: 17.978
[1,  3947] Training loss: 17.973
[1,  3948] Training loss: 17.969
[1,  3949] Training loss: 17.965
[1,  3950] Training loss: 17.961
[1,  3951] Training loss: 17.957
[1,  3952] Training loss: 17.953
[1,  3953] Training loss: 17.948
[1,  3954] Training loss: 17.944
[1,  3955] Training loss: 17.940
[1,  3956] Training loss: 17.936
[1,  3957] Training loss: 17.932
[1,  3958] Training loss: 17.928
[1,  3959] Training loss: 17.923
[1,  3960] Training loss: 17.919
[1,  3961] Training loss: 17.915
[1,  3962] Training loss: 17.911
[1,  3963] Training loss: 17.907
[1,  3964] Training loss: 17.902
[1,  3965] Training loss: 17.898
[1,  3966] Training loss: 17.894
[1,  3967] Training loss: 17.890
[1,  3968] Training loss: 17.886
[1,  3969] Training loss: 17.882
[1,  3970] Training loss: 17.878
[1,  3971] Training loss: 17.874
[1,  3972] Training loss: 17.870
[1,  3973] Training loss: 17.865
[1,  3974]

[1,  4209] Training loss: 16.964
[1,  4210] Training loss: 16.960
[1,  4211] Training loss: 16.957
[1,  4212] Training loss: 16.954
[1,  4213] Training loss: 16.950
[1,  4214] Training loss: 16.946
[1,  4215] Training loss: 16.943
[1,  4216] Training loss: 16.939
[1,  4217] Training loss: 16.936
[1,  4218] Training loss: 16.933
[1,  4219] Training loss: 16.929
[1,  4220] Training loss: 16.926
[1,  4221] Training loss: 16.922
[1,  4222] Training loss: 16.918
[1,  4223] Training loss: 16.914
[1,  4224] Training loss: 16.911
[1,  4225] Training loss: 16.908
[1,  4226] Training loss: 16.905
[1,  4227] Training loss: 16.901
[1,  4228] Training loss: 16.898
[1,  4229] Training loss: 16.895
[1,  4230] Training loss: 16.891
[1,  4231] Training loss: 16.887
[1,  4232] Training loss: 16.883
[1,  4233] Training loss: 16.880
[1,  4234] Training loss: 16.877
[1,  4235] Training loss: 16.873
[1,  4236] Training loss: 16.870
[1,  4237] Training loss: 16.866
[1,  4238] Training loss: 16.862
[1,  4239]

[1,  4473] Training loss: 16.069
[1,  4474] Training loss: 16.066
[1,  4475] Training loss: 16.063
[1,  4476] Training loss: 16.059
[1,  4477] Training loss: 16.056
[1,  4478] Training loss: 16.053
[1,  4479] Training loss: 16.050
[1,  4480] Training loss: 16.047
[1,  4481] Training loss: 16.043
[1,  4482] Training loss: 16.040
[1,  4483] Training loss: 16.037
[1,  4484] Training loss: 16.033
[1,  4485] Training loss: 16.030
[1,  4486] Training loss: 16.028
[1,  4487] Training loss: 16.024
[1,  4488] Training loss: 16.021
[1,  4489] Training loss: 16.018
[1,  4490] Training loss: 16.014
[1,  4491] Training loss: 16.011
[1,  4492] Training loss: 16.008
[1,  4493] Training loss: 16.005
[1,  4494] Training loss: 16.002
[1,  4495] Training loss: 15.999
[1,  4496] Training loss: 15.996
[1,  4497] Training loss: 15.992
[1,  4498] Training loss: 15.989
[1,  4499] Training loss: 15.986
[1,  4500] Training loss: 15.984
[1,  4501] Training loss: 15.981
[1,  4502] Training loss: 15.977
[1,  4503]

[1,  4738] Training loss: 15.277
[1,  4739] Training loss: 15.274
[1,  4740] Training loss: 15.271
[1,  4741] Training loss: 15.268
[1,  4742] Training loss: 15.265
[1,  4743] Training loss: 15.262
[1,  4744] Training loss: 15.259
[1,  4745] Training loss: 15.256
[1,  4746] Training loss: 15.253
[1,  4747] Training loss: 15.250
[1,  4748] Training loss: 15.247
[1,  4749] Training loss: 15.244
[1,  4750] Training loss: 15.242
[1,  4751] Training loss: 15.239
[1,  4752] Training loss: 15.236
[1,  4753] Training loss: 15.233
[1,  4754] Training loss: 15.230
[1,  4755] Training loss: 15.227
[1,  4756] Training loss: 15.225
[1,  4757] Training loss: 15.222
[1,  4758] Training loss: 15.219
[1,  4759] Training loss: 15.216
[1,  4760] Training loss: 15.214
[1,  4761] Training loss: 15.212
[1,  4762] Training loss: 15.209
[1,  4763] Training loss: 15.206
[1,  4764] Training loss: 15.203
[1,  4765] Training loss: 15.201
[1,  4766] Training loss: 15.198
[1,  4767] Training loss: 15.195
[1,  4768]

[1,  5003] Training loss: 14.568
[1,  5004] Training loss: 14.566
[1,  5005] Training loss: 14.563
[1,  5006] Training loss: 14.561
[1,  5007] Training loss: 14.558
[1,  5008] Training loss: 14.556
[1,  5009] Training loss: 14.553
[1,  5010] Training loss: 14.551
[1,  5011] Training loss: 14.548
[1,  5012] Training loss: 14.545
[1,  5013] Training loss: 14.543
[1,  5014] Training loss: 14.540
[1,  5015] Training loss: 14.538
[1,  5016] Training loss: 14.535
[1,  5017] Training loss: 14.533
[1,  5018] Training loss: 14.530
[1,  5019] Training loss: 14.528
[1,  5020] Training loss: 14.525
[1,  5021] Training loss: 14.522
[1,  5022] Training loss: 14.520
[1,  5023] Training loss: 14.517
[1,  5024] Training loss: 14.514
[1,  5025] Training loss: 14.512
[1,  5026] Training loss: 14.509
[1,  5027] Training loss: 14.507
[1,  5028] Training loss: 14.504
[1,  5029] Training loss: 14.502
[1,  5030] Training loss: 14.499
[1,  5031] Training loss: 14.497
[1,  5032] Training loss: 14.494
[1,  5033]

[1,  5269] Training loss: 13.925
[1,  5270] Training loss: 13.923
[1,  5271] Training loss: 13.920
[1,  5272] Training loss: 13.918
[1,  5273] Training loss: 13.916
[1,  5274] Training loss: 13.913
[1,  5275] Training loss: 13.911
[1,  5276] Training loss: 13.909
[1,  5277] Training loss: 13.907
[1,  5278] Training loss: 13.904
[1,  5279] Training loss: 13.902
[1,  5280] Training loss: 13.900
[1,  5281] Training loss: 13.897
[1,  5282] Training loss: 13.895
[1,  5283] Training loss: 13.893
[1,  5284] Training loss: 13.891
[1,  5285] Training loss: 13.888
[1,  5286] Training loss: 13.886
[1,  5287] Training loss: 13.884
[1,  5288] Training loss: 13.881
[1,  5289] Training loss: 13.879
[1,  5290] Training loss: 13.877
[1,  5291] Training loss: 13.875
[1,  5292] Training loss: 13.873
[1,  5293] Training loss: 13.871
[1,  5294] Training loss: 13.869
[1,  5295] Training loss: 13.866
[1,  5296] Training loss: 13.864
[1,  5297] Training loss: 13.862
[1,  5298] Training loss: 13.860
[1,  5299]

[1,  5534] Training loss: 13.347
[1,  5535] Training loss: 13.345
[1,  5536] Training loss: 13.343
[1,  5537] Training loss: 13.341
[1,  5538] Training loss: 13.339
[1,  5539] Training loss: 13.337
[1,  5540] Training loss: 13.335
[1,  5541] Training loss: 13.333
[1,  5542] Training loss: 13.331
[1,  5543] Training loss: 13.329
[1,  5544] Training loss: 13.327
[1,  5545] Training loss: 13.325
[1,  5546] Training loss: 13.322
[1,  5547] Training loss: 13.320
[1,  5548] Training loss: 13.319
[1,  5549] Training loss: 13.316
[1,  5550] Training loss: 13.314
[1,  5551] Training loss: 13.312
[1,  5552] Training loss: 13.310
[1,  5553] Training loss: 13.308
[1,  5554] Training loss: 13.306
[1,  5555] Training loss: 13.304
[1,  5556] Training loss: 13.302
[1,  5557] Training loss: 13.300
[1,  5558] Training loss: 13.298
[1,  5559] Training loss: 13.296
[1,  5560] Training loss: 13.294
[1,  5561] Training loss: 13.292
[1,  5562] Training loss: 13.290
[1,  5563] Training loss: 13.288
[1,  5564]

[1,  5800] Training loss: 12.819
[1,  5801] Training loss: 12.817
[1,  5802] Training loss: 12.815
[1,  5803] Training loss: 12.813
[1,  5804] Training loss: 12.811
[1,  5805] Training loss: 12.809
[1,  5806] Training loss: 12.807
[1,  5807] Training loss: 12.806
[1,  5808] Training loss: 12.804
[1,  5809] Training loss: 12.802
[1,  5810] Training loss: 12.800
[1,  5811] Training loss: 12.798
[1,  5812] Training loss: 12.796
[1,  5813] Training loss: 12.794
[1,  5814] Training loss: 12.793
[1,  5815] Training loss: 12.791
[1,  5816] Training loss: 12.789
[1,  5817] Training loss: 12.787
[1,  5818] Training loss: 12.785
[1,  5819] Training loss: 12.783
[1,  5820] Training loss: 12.782
[1,  5821] Training loss: 12.780
[1,  5822] Training loss: 12.778
[1,  5823] Training loss: 12.776
[1,  5824] Training loss: 12.774
[1,  5825] Training loss: 12.772
[1,  5826] Training loss: 12.770
[1,  5827] Training loss: 12.768
[1,  5828] Training loss: 12.766
[1,  5829] Training loss: 12.764
[1,  5830]

[1,  6066] Training loss: 12.339
[1,  6067] Training loss: 12.337
[1,  6068] Training loss: 12.335
[1,  6069] Training loss: 12.334
[1,  6070] Training loss: 12.332
[1,  6071] Training loss: 12.330
[1,  6072] Training loss: 12.328
[1,  6073] Training loss: 12.327
[1,  6074] Training loss: 12.325
[1,  6075] Training loss: 12.323
[1,  6076] Training loss: 12.321
[1,  6077] Training loss: 12.319
[1,  6078] Training loss: 12.318
[1,  6079] Training loss: 12.316
[1,  6080] Training loss: 12.314
[1,  6081] Training loss: 12.313
[1,  6082] Training loss: 12.311
[1,  6083] Training loss: 12.310
[1,  6084] Training loss: 12.308
[1,  6085] Training loss: 12.306
[1,  6086] Training loss: 12.305
[1,  6087] Training loss: 12.303
[1,  6088] Training loss: 12.301
[1,  6089] Training loss: 12.300
[1,  6090] Training loss: 12.298
[1,  6091] Training loss: 12.296
[1,  6092] Training loss: 12.294
[1,  6093] Training loss: 12.293
[1,  6094] Training loss: 12.291
[1,  6095] Training loss: 12.289
[1,  6096]

[1,  6324] Training loss: 11.911
[1,  6325] Training loss: 11.909
[1,  6326] Training loss: 11.908
[1,  6327] Training loss: 11.906
[1,  6328] Training loss: 11.904
[1,  6329] Training loss: 11.903
[1,  6330] Training loss: 11.901
[1,  6331] Training loss: 11.899
[1,  6332] Training loss: 11.898
[1,  6333] Training loss: 11.896
[1,  6334] Training loss: 11.895
[1,  6335] Training loss: 11.893
[1,  6336] Training loss: 11.892
[1,  6337] Training loss: 11.890
[1,  6338] Training loss: 11.888
[1,  6339] Training loss: 11.887
[1,  6340] Training loss: 11.885
[1,  6341] Training loss: 11.884
[1,  6342] Training loss: 11.882
[1,  6343] Training loss: 11.880
[1,  6344] Training loss: 11.879
[1,  6345] Training loss: 11.877
[1,  6346] Training loss: 11.876
[1,  6347] Training loss: 11.874
[1,  6348] Training loss: 11.872
[1,  6349] Training loss: 11.871
[1,  6350] Training loss: 11.869
[1,  6351] Training loss: 11.868
[1,  6352] Training loss: 11.866
[1,  6353] Training loss: 11.865
[1,  6354]

[1,  6584] Training loss: 11.514
[1,  6585] Training loss: 11.512
[1,  6586] Training loss: 11.511
[1,  6587] Training loss: 11.509
[1,  6588] Training loss: 11.508
[1,  6589] Training loss: 11.506
[1,  6590] Training loss: 11.505
[1,  6591] Training loss: 11.503
[1,  6592] Training loss: 11.502
[1,  6593] Training loss: 11.500
[1,  6594] Training loss: 11.499
[1,  6595] Training loss: 11.497
[1,  6596] Training loss: 11.496
[1,  6597] Training loss: 11.494
[1,  6598] Training loss: 11.493
[1,  6599] Training loss: 11.492
[1,  6600] Training loss: 11.490
[1,  6601] Training loss: 11.489
[1,  6602] Training loss: 11.487
[1,  6603] Training loss: 11.486
[1,  6604] Training loss: 11.484
[1,  6605] Training loss: 11.483
[1,  6606] Training loss: 11.482
[1,  6607] Training loss: 11.480
[1,  6608] Training loss: 11.479
[1,  6609] Training loss: 11.478
[1,  6610] Training loss: 11.476
[1,  6611] Training loss: 11.475
[1,  6612] Training loss: 11.473
[1,  6613] Training loss: 11.472
[1,  6614]

[1,  6850] Training loss: 11.137
[1,  6851] Training loss: 11.135
[1,  6852] Training loss: 11.134
[1,  6853] Training loss: 11.132
[1,  6854] Training loss: 11.131
[1,  6855] Training loss: 11.130
[1,  6856] Training loss: 11.128
[1,  6857] Training loss: 11.127
[1,  6858] Training loss: 11.126
[1,  6859] Training loss: 11.124
[1,  6860] Training loss: 11.123
[1,  6861] Training loss: 11.121
[1,  6862] Training loss: 11.120
[1,  6863] Training loss: 11.119
[1,  6864] Training loss: 11.118
[1,  6865] Training loss: 11.116
[1,  6866] Training loss: 11.115
[1,  6867] Training loss: 11.114
[1,  6868] Training loss: 11.112
[1,  6869] Training loss: 11.111
[1,  6870] Training loss: 11.110
[1,  6871] Training loss: 11.108
[1,  6872] Training loss: 11.107
[1,  6873] Training loss: 11.106
[1,  6874] Training loss: 11.104
[1,  6875] Training loss: 11.103
[1,  6876] Training loss: 11.101
[1,  6877] Training loss: 11.100
[1,  6878] Training loss: 11.098
[1,  6879] Training loss: 11.097
[1,  6880]

[1,  7114] Training loss: 10.792
[1,  7115] Training loss: 10.791
[1,  7116] Training loss: 10.790
[1,  7117] Training loss: 10.789
[1,  7118] Training loss: 10.788
[1,  7119] Training loss: 10.786
[1,  7120] Training loss: 10.785
[1,  7121] Training loss: 10.784
[1,  7122] Training loss: 10.782
[1,  7123] Training loss: 10.781
[1,  7124] Training loss: 10.780
[1,  7125] Training loss: 10.779
[1,  7126] Training loss: 10.777
[1,  7127] Training loss: 10.776
[1,  7128] Training loss: 10.774
[1,  7129] Training loss: 10.773
[1,  7130] Training loss: 10.772
[1,  7131] Training loss: 10.771
[1,  7132] Training loss: 10.769
[1,  7133] Training loss: 10.768
[1,  7134] Training loss: 10.767
[1,  7135] Training loss: 10.765
[1,  7136] Training loss: 10.764
[1,  7137] Training loss: 10.763
[1,  7138] Training loss: 10.762
[1,  7139] Training loss: 10.760
[1,  7140] Training loss: 10.759
[1,  7141] Training loss: 10.757
[1,  7142] Training loss: 10.756
[1,  7143] Training loss: 10.755
[1,  7144]

[1,  7378] Training loss: 10.471
[1,  7379] Training loss: 10.470
[1,  7380] Training loss: 10.469
[1,  7381] Training loss: 10.468
[1,  7382] Training loss: 10.467
[1,  7383] Training loss: 10.465
[1,  7384] Training loss: 10.464
[1,  7385] Training loss: 10.463
[1,  7386] Training loss: 10.462
[1,  7387] Training loss: 10.461
[1,  7388] Training loss: 10.460
[1,  7389] Training loss: 10.459
[1,  7390] Training loss: 10.457
[1,  7391] Training loss: 10.456
[1,  7392] Training loss: 10.455
[1,  7393] Training loss: 10.454
[1,  7394] Training loss: 10.453
[1,  7395] Training loss: 10.452
[1,  7396] Training loss: 10.451
[1,  7397] Training loss: 10.449
[1,  7398] Training loss: 10.449
[1,  7399] Training loss: 10.447
[1,  7400] Training loss: 10.446
[1,  7401] Training loss: 10.445
[1,  7402] Training loss: 10.443
[1,  7403] Training loss: 10.442
[1,  7404] Training loss: 10.441
[1,  7405] Training loss: 10.440
[1,  7406] Training loss: 10.439
[1,  7407] Training loss: 10.437
[1,  7408]

[1,  7642] Training loss: 10.175
[1,  7643] Training loss: 10.174
[1,  7644] Training loss: 10.173
[1,  7645] Training loss: 10.172
[1,  7646] Training loss: 10.171
[1,  7647] Training loss: 10.170
[1,  7648] Training loss: 10.169
[1,  7649] Training loss: 10.168
[1,  7650] Training loss: 10.166
[1,  7651] Training loss: 10.165
[1,  7652] Training loss: 10.164
[1,  7653] Training loss: 10.163
[1,  7654] Training loss: 10.162
[1,  7655] Training loss: 10.161
[1,  7656] Training loss: 10.160
[1,  7657] Training loss: 10.158
[1,  7658] Training loss: 10.157
[1,  7659] Training loss: 10.156
[1,  7660] Training loss: 10.155
[1,  7661] Training loss: 10.154
[1,  7662] Training loss: 10.153
[1,  7663] Training loss: 10.152
[1,  7664] Training loss: 10.151
[1,  7665] Training loss: 10.150
[1,  7666] Training loss: 10.148
[1,  7667] Training loss: 10.147
[1,  7668] Training loss: 10.146
[1,  7669] Training loss: 10.145
[1,  7670] Training loss: 10.144
[1,  7671] Training loss: 10.143
[1,  7672]

[1,  7906] Training loss: 9.895
[1,  7907] Training loss: 9.894
[1,  7908] Training loss: 9.894
[1,  7909] Training loss: 9.892
[1,  7910] Training loss: 9.892
[1,  7911] Training loss: 9.891
[1,  7912] Training loss: 9.890
[1,  7913] Training loss: 9.889
[1,  7914] Training loss: 9.888
[1,  7915] Training loss: 9.887
[1,  7916] Training loss: 9.886
[1,  7917] Training loss: 9.885
[1,  7918] Training loss: 9.884
[1,  7919] Training loss: 9.883
[1,  7920] Training loss: 9.882
[1,  7921] Training loss: 9.881
[1,  7922] Training loss: 9.880
[1,  7923] Training loss: 9.879
[1,  7924] Training loss: 9.878
[1,  7925] Training loss: 9.877
[1,  7926] Training loss: 9.876
[1,  7927] Training loss: 9.875
[1,  7928] Training loss: 9.874
[1,  7929] Training loss: 9.873
[1,  7930] Training loss: 9.872
[1,  7931] Training loss: 9.871
[1,  7932] Training loss: 9.870
[1,  7933] Training loss: 9.870
[1,  7934] Training loss: 9.868
[1,  7935] Training loss: 9.868
[1,  7936] Training loss: 9.867
[1,  793

[1,  8170] Training loss: 9.639
[1,  8171] Training loss: 9.638
[1,  8172] Training loss: 9.637
[1,  8173] Training loss: 9.636
[1,  8174] Training loss: 9.635
[1,  8175] Training loss: 9.634
[1,  8176] Training loss: 9.633
[1,  8177] Training loss: 9.632
[1,  8178] Training loss: 9.631
[1,  8179] Training loss: 9.630
[1,  8180] Training loss: 9.629
[1,  8181] Training loss: 9.628
[1,  8182] Training loss: 9.627
[1,  8183] Training loss: 9.626
[1,  8184] Training loss: 9.625
[1,  8185] Training loss: 9.624
[1,  8186] Training loss: 9.623
[1,  8187] Training loss: 9.622
[1,  8188] Training loss: 9.621
[1,  8189] Training loss: 9.620
[1,  8190] Training loss: 9.620
[1,  8191] Training loss: 9.619
[1,  8192] Training loss: 9.618
[1,  8193] Training loss: 9.617
[1,  8194] Training loss: 9.616
[1,  8195] Training loss: 9.615
[1,  8196] Training loss: 9.614
[1,  8197] Training loss: 9.614
[1,  8198] Training loss: 9.613
[1,  8199] Training loss: 9.611
[1,  8200] Training loss: 9.611
[1,  820

[1,  8434] Training loss: 9.395
[1,  8435] Training loss: 9.394
[1,  8436] Training loss: 9.393
[1,  8437] Training loss: 9.392
[1,  8438] Training loss: 9.391
[1,  8439] Training loss: 9.390
[1,  8440] Training loss: 9.389
[1,  8441] Training loss: 9.388
[1,  8442] Training loss: 9.387
[1,  8443] Training loss: 9.386
[1,  8444] Training loss: 9.385
[1,  8445] Training loss: 9.384
[1,  8446] Training loss: 9.384
[1,  8447] Training loss: 9.383
[1,  8448] Training loss: 9.382
[1,  8449] Training loss: 9.381
[1,  8450] Training loss: 9.380
[1,  8451] Training loss: 9.379
[1,  8452] Training loss: 9.378
[1,  8453] Training loss: 9.377
[1,  8454] Training loss: 9.377
[1,  8455] Training loss: 9.376
[1,  8456] Training loss: 9.375
[1,  8457] Training loss: 9.374
[1,  8458] Training loss: 9.373
[1,  8459] Training loss: 9.372
[1,  8460] Training loss: 9.371
[1,  8461] Training loss: 9.370
[1,  8462] Training loss: 9.369
[1,  8463] Training loss: 9.368
[1,  8464] Training loss: 9.367
[1,  846

[2,   145] Training loss: 1.804
[2,   146] Training loss: 1.803
[2,   147] Training loss: 1.800
[2,   148] Training loss: 1.805
[2,   149] Training loss: 1.808
[2,   150] Training loss: 1.807
[2,   151] Training loss: 1.807
[2,   152] Training loss: 1.801
[2,   153] Training loss: 1.795
[2,   154] Training loss: 1.800
[2,   155] Training loss: 1.805
[2,   156] Training loss: 1.804
[2,   157] Training loss: 1.815
[2,   158] Training loss: 1.809
[2,   159] Training loss: 1.811
[2,   160] Training loss: 1.800
[2,   161] Training loss: 1.802
[2,   162] Training loss: 1.812
[2,   163] Training loss: 1.809
[2,   164] Training loss: 1.801
[2,   165] Training loss: 1.798
[2,   166] Training loss: 1.798
[2,   167] Training loss: 1.802
[2,   168] Training loss: 1.794
[2,   169] Training loss: 1.799
[2,   170] Training loss: 1.799
[2,   171] Training loss: 1.806
[2,   172] Training loss: 1.805
[2,   173] Training loss: 1.805
[2,   174] Training loss: 1.804
[2,   175] Training loss: 1.809
[2,   17

[2,   409] Training loss: 1.788
[2,   410] Training loss: 1.787
[2,   411] Training loss: 1.784
[2,   412] Training loss: 1.786
[2,   413] Training loss: 1.789
[2,   414] Training loss: 1.788
[2,   415] Training loss: 1.786
[2,   416] Training loss: 1.785
[2,   417] Training loss: 1.781
[2,   418] Training loss: 1.781
[2,   419] Training loss: 1.781
[2,   420] Training loss: 1.781
[2,   421] Training loss: 1.781
[2,   422] Training loss: 1.780
[2,   423] Training loss: 1.779
[2,   424] Training loss: 1.779
[2,   425] Training loss: 1.777
[2,   426] Training loss: 1.777
[2,   427] Training loss: 1.779
[2,   428] Training loss: 1.780
[2,   429] Training loss: 1.785
[2,   430] Training loss: 1.786
[2,   431] Training loss: 1.788
[2,   432] Training loss: 1.794
[2,   433] Training loss: 1.793
[2,   434] Training loss: 1.792
[2,   435] Training loss: 1.795
[2,   436] Training loss: 1.797
[2,   437] Training loss: 1.802
[2,   438] Training loss: 1.802
[2,   439] Training loss: 1.805
[2,   44

[2,   673] Training loss: 1.838
[2,   674] Training loss: 1.836
[2,   675] Training loss: 1.835
[2,   676] Training loss: 1.835
[2,   677] Training loss: 1.835
[2,   678] Training loss: 1.836
[2,   679] Training loss: 1.834
[2,   680] Training loss: 1.833
[2,   681] Training loss: 1.833
[2,   682] Training loss: 1.833
[2,   683] Training loss: 1.833
[2,   684] Training loss: 1.831
[2,   685] Training loss: 1.831
[2,   686] Training loss: 1.833
[2,   687] Training loss: 1.832
[2,   688] Training loss: 1.830
[2,   689] Training loss: 1.830
[2,   690] Training loss: 1.830
[2,   691] Training loss: 1.833
[2,   692] Training loss: 1.834
[2,   693] Training loss: 1.835
[2,   694] Training loss: 1.834
[2,   695] Training loss: 1.833
[2,   696] Training loss: 1.832
[2,   697] Training loss: 1.832
[2,   698] Training loss: 1.833
[2,   699] Training loss: 1.834
[2,   700] Training loss: 1.836
[2,   701] Training loss: 1.835
[2,   702] Training loss: 1.835
[2,   703] Training loss: 1.837
[2,   70

[2,   937] Training loss: 1.833
[2,   938] Training loss: 1.833
[2,   939] Training loss: 1.831
[2,   940] Training loss: 1.832
[2,   941] Training loss: 1.835
[2,   942] Training loss: 1.835
[2,   943] Training loss: 1.835
[2,   944] Training loss: 1.835
[2,   945] Training loss: 1.836
[2,   946] Training loss: 1.835
[2,   947] Training loss: 1.836
[2,   948] Training loss: 1.836
[2,   949] Training loss: 1.836
[2,   950] Training loss: 1.836
[2,   951] Training loss: 1.835
[2,   952] Training loss: 1.837
[2,   953] Training loss: 1.839
[2,   954] Training loss: 1.840
[2,   955] Training loss: 1.839
[2,   956] Training loss: 1.839
[2,   957] Training loss: 1.840
[2,   958] Training loss: 1.840
[2,   959] Training loss: 1.841
[2,   960] Training loss: 1.841
[2,   961] Training loss: 1.843
[2,   962] Training loss: 1.843
[2,   963] Training loss: 1.842
[2,   964] Training loss: 1.842
[2,   965] Training loss: 1.843
[2,   966] Training loss: 1.843
[2,   967] Training loss: 1.844
[2,   96

[2,  1202] Training loss: 1.854
[2,  1203] Training loss: 1.854
[2,  1204] Training loss: 1.853
[2,  1205] Training loss: 1.854
[2,  1206] Training loss: 1.854
[2,  1207] Training loss: 1.853
[2,  1208] Training loss: 1.853
[2,  1209] Training loss: 1.853
[2,  1210] Training loss: 1.852
[2,  1211] Training loss: 1.852
[2,  1212] Training loss: 1.852
[2,  1213] Training loss: 1.851
[2,  1214] Training loss: 1.852
[2,  1215] Training loss: 1.852
[2,  1216] Training loss: 1.853
[2,  1217] Training loss: 1.852
[2,  1218] Training loss: 1.852
[2,  1219] Training loss: 1.853
[2,  1220] Training loss: 1.852
[2,  1221] Training loss: 1.852
[2,  1222] Training loss: 1.853
[2,  1223] Training loss: 1.853
[2,  1224] Training loss: 1.852
[2,  1225] Training loss: 1.852
[2,  1226] Training loss: 1.852
[2,  1227] Training loss: 1.852
[2,  1228] Training loss: 1.851
[2,  1229] Training loss: 1.852
[2,  1230] Training loss: 1.852
[2,  1231] Training loss: 1.850
[2,  1232] Training loss: 1.851
[2,  123

[2,  1466] Training loss: 1.848
[2,  1467] Training loss: 1.848
[2,  1468] Training loss: 1.848
[2,  1469] Training loss: 1.848
[2,  1470] Training loss: 1.849
[2,  1471] Training loss: 1.849
[2,  1472] Training loss: 1.849
[2,  1473] Training loss: 1.848
[2,  1474] Training loss: 1.848
[2,  1475] Training loss: 1.847
[2,  1476] Training loss: 1.848
[2,  1477] Training loss: 1.848
[2,  1478] Training loss: 1.848
[2,  1479] Training loss: 1.847
[2,  1480] Training loss: 1.848
[2,  1481] Training loss: 1.848
[2,  1482] Training loss: 1.848
[2,  1483] Training loss: 1.848
[2,  1484] Training loss: 1.848
[2,  1485] Training loss: 1.848
[2,  1486] Training loss: 1.847
[2,  1487] Training loss: 1.847
[2,  1488] Training loss: 1.847
[2,  1489] Training loss: 1.846
[2,  1490] Training loss: 1.846
[2,  1491] Training loss: 1.846
[2,  1492] Training loss: 1.846
[2,  1493] Training loss: 1.845
[2,  1494] Training loss: 1.845
[2,  1495] Training loss: 1.846
[2,  1496] Training loss: 1.847
[2,  149

[2,  1730] Training loss: 1.856
[2,  1731] Training loss: 1.856
[2,  1732] Training loss: 1.855
[2,  1733] Training loss: 1.856
[2,  1734] Training loss: 1.855
[2,  1735] Training loss: 1.856
[2,  1736] Training loss: 1.856
[2,  1737] Training loss: 1.856
[2,  1738] Training loss: 1.856
[2,  1739] Training loss: 1.855
[2,  1740] Training loss: 1.855
[2,  1741] Training loss: 1.855
[2,  1742] Training loss: 1.855
[2,  1743] Training loss: 1.856
[2,  1744] Training loss: 1.855
[2,  1745] Training loss: 1.856
[2,  1746] Training loss: 1.855
[2,  1747] Training loss: 1.856
[2,  1748] Training loss: 1.856
[2,  1749] Training loss: 1.856
[2,  1750] Training loss: 1.856
[2,  1751] Training loss: 1.856
[2,  1752] Training loss: 1.856
[2,  1753] Training loss: 1.855
[2,  1754] Training loss: 1.855
[2,  1755] Training loss: 1.854
[2,  1756] Training loss: 1.854
[2,  1757] Training loss: 1.853
[2,  1758] Training loss: 1.854
[2,  1759] Training loss: 1.854
[2,  1760] Training loss: 1.855
[2,  176

[2,  1994] Training loss: 1.844
[2,  1995] Training loss: 1.844
[2,  1996] Training loss: 1.843
[2,  1997] Training loss: 1.843
[2,  1998] Training loss: 1.843
[2,  1999] Training loss: 1.844
[2,  2000] Training loss: 1.844
[2,  2001] Training loss: 1.844
[2,  2002] Training loss: 1.844
[2,  2003] Training loss: 1.843
[2,  2004] Training loss: 1.843
[2,  2005] Training loss: 1.843
[2,  2006] Training loss: 1.843
[2,  2007] Training loss: 1.842
[2,  2008] Training loss: 1.842
[2,  2009] Training loss: 1.843
[2,  2010] Training loss: 1.843
[2,  2011] Training loss: 1.843
[2,  2012] Training loss: 1.843
[2,  2013] Training loss: 1.842
[2,  2014] Training loss: 1.843
[2,  2015] Training loss: 1.843
[2,  2016] Training loss: 1.843
[2,  2017] Training loss: 1.843
[2,  2018] Training loss: 1.843
[2,  2019] Training loss: 1.844
[2,  2020] Training loss: 1.844
[2,  2021] Training loss: 1.844
[2,  2022] Training loss: 1.844
[2,  2023] Training loss: 1.844
[2,  2024] Training loss: 1.843
[2,  202

[2,  2258] Training loss: 1.844
[2,  2259] Training loss: 1.844
[2,  2260] Training loss: 1.845
[2,  2261] Training loss: 1.845
[2,  2262] Training loss: 1.845
[2,  2263] Training loss: 1.844
[2,  2264] Training loss: 1.845
[2,  2265] Training loss: 1.845
[2,  2266] Training loss: 1.844
[2,  2267] Training loss: 1.844
[2,  2268] Training loss: 1.844
[2,  2269] Training loss: 1.843
[2,  2270] Training loss: 1.843
[2,  2271] Training loss: 1.844
[2,  2272] Training loss: 1.843
[2,  2273] Training loss: 1.843
[2,  2274] Training loss: 1.843
[2,  2275] Training loss: 1.843
[2,  2276] Training loss: 1.843
[2,  2277] Training loss: 1.842
[2,  2278] Training loss: 1.842
[2,  2279] Training loss: 1.842
[2,  2280] Training loss: 1.842
[2,  2281] Training loss: 1.842
[2,  2282] Training loss: 1.842
[2,  2283] Training loss: 1.842
[2,  2284] Training loss: 1.843
[2,  2285] Training loss: 1.842
[2,  2286] Training loss: 1.842
[2,  2287] Training loss: 1.843
[2,  2288] Training loss: 1.843
[2,  228

[2,  2522] Training loss: 1.834
[2,  2523] Training loss: 1.834
[2,  2524] Training loss: 1.835
[2,  2525] Training loss: 1.834
[2,  2526] Training loss: 1.834
[2,  2527] Training loss: 1.833
[2,  2528] Training loss: 1.834
[2,  2529] Training loss: 1.834
[2,  2530] Training loss: 1.835
[2,  2531] Training loss: 1.835
[2,  2532] Training loss: 1.835
[2,  2533] Training loss: 1.834
[2,  2534] Training loss: 1.835
[2,  2535] Training loss: 1.835
[2,  2536] Training loss: 1.836
[2,  2537] Training loss: 1.836
[2,  2538] Training loss: 1.836
[2,  2539] Training loss: 1.837
[2,  2540] Training loss: 1.837
[2,  2541] Training loss: 1.837
[2,  2542] Training loss: 1.838
[2,  2543] Training loss: 1.837
[2,  2544] Training loss: 1.838
[2,  2545] Training loss: 1.838
[2,  2546] Training loss: 1.837
[2,  2547] Training loss: 1.838
[2,  2548] Training loss: 1.838
[2,  2549] Training loss: 1.837
[2,  2550] Training loss: 1.837
[2,  2551] Training loss: 1.837
[2,  2552] Training loss: 1.837
[2,  255

[2,  2786] Training loss: 1.836
[2,  2787] Training loss: 1.837
[2,  2788] Training loss: 1.837
[2,  2789] Training loss: 1.838
[2,  2790] Training loss: 1.838
[2,  2791] Training loss: 1.839
[2,  2792] Training loss: 1.838
[2,  2793] Training loss: 1.838
[2,  2794] Training loss: 1.839
[2,  2795] Training loss: 1.839
[2,  2796] Training loss: 1.838
[2,  2797] Training loss: 1.838
[2,  2798] Training loss: 1.839
[2,  2799] Training loss: 1.839
[2,  2800] Training loss: 1.839
[2,  2801] Training loss: 1.839
[2,  2802] Training loss: 1.839
[2,  2803] Training loss: 1.839
[2,  2804] Training loss: 1.839
[2,  2805] Training loss: 1.839
[2,  2806] Training loss: 1.839
[2,  2807] Training loss: 1.839
[2,  2808] Training loss: 1.839
[2,  2809] Training loss: 1.839
[2,  2810] Training loss: 1.839
[2,  2811] Training loss: 1.839
[2,  2812] Training loss: 1.839
[2,  2813] Training loss: 1.839
[2,  2814] Training loss: 1.839
[2,  2815] Training loss: 1.839
[2,  2816] Training loss: 1.839
[2,  281

[2,  3050] Training loss: 1.845
[2,  3051] Training loss: 1.845
[2,  3052] Training loss: 1.845
[2,  3053] Training loss: 1.845
[2,  3054] Training loss: 1.845
[2,  3055] Training loss: 1.844
[2,  3056] Training loss: 1.845
[2,  3057] Training loss: 1.845
[2,  3058] Training loss: 1.844
[2,  3059] Training loss: 1.844
[2,  3060] Training loss: 1.844
[2,  3061] Training loss: 1.844
[2,  3062] Training loss: 1.844
[2,  3063] Training loss: 1.844
[2,  3064] Training loss: 1.844
[2,  3065] Training loss: 1.844
[2,  3066] Training loss: 1.844
[2,  3067] Training loss: 1.843
[2,  3068] Training loss: 1.844
[2,  3069] Training loss: 1.844
[2,  3070] Training loss: 1.844
[2,  3071] Training loss: 1.845
[2,  3072] Training loss: 1.845
[2,  3073] Training loss: 1.844
[2,  3074] Training loss: 1.844
[2,  3075] Training loss: 1.844
[2,  3076] Training loss: 1.844
[2,  3077] Training loss: 1.844
[2,  3078] Training loss: 1.844
[2,  3079] Training loss: 1.844
[2,  3080] Training loss: 1.844
[2,  308

[2,  3314] Training loss: 1.838
[2,  3315] Training loss: 1.838
[2,  3316] Training loss: 1.838
[2,  3317] Training loss: 1.838
[2,  3318] Training loss: 1.838
[2,  3319] Training loss: 1.838
[2,  3320] Training loss: 1.839
[2,  3321] Training loss: 1.838
[2,  3322] Training loss: 1.838
[2,  3323] Training loss: 1.838
[2,  3324] Training loss: 1.839
[2,  3325] Training loss: 1.839
[2,  3326] Training loss: 1.839
[2,  3327] Training loss: 1.839
[2,  3328] Training loss: 1.840
[2,  3329] Training loss: 1.840
[2,  3330] Training loss: 1.840
[2,  3331] Training loss: 1.840
[2,  3332] Training loss: 1.840
[2,  3333] Training loss: 1.840
[2,  3334] Training loss: 1.840
[2,  3335] Training loss: 1.840
[2,  3336] Training loss: 1.840
[2,  3337] Training loss: 1.840
[2,  3338] Training loss: 1.840
[2,  3339] Training loss: 1.840
[2,  3340] Training loss: 1.840
[2,  3341] Training loss: 1.840
[2,  3342] Training loss: 1.840
[2,  3343] Training loss: 1.841
[2,  3344] Training loss: 1.841
[2,  334

[2,  3578] Training loss: 1.840
[2,  3579] Training loss: 1.840
[2,  3580] Training loss: 1.840
[2,  3581] Training loss: 1.840
[2,  3582] Training loss: 1.841
[2,  3583] Training loss: 1.840
[2,  3584] Training loss: 1.840
[2,  3585] Training loss: 1.840
[2,  3586] Training loss: 1.840
[2,  3587] Training loss: 1.840
[2,  3588] Training loss: 1.840
[2,  3589] Training loss: 1.840
[2,  3590] Training loss: 1.840
[2,  3591] Training loss: 1.840
[2,  3592] Training loss: 1.839
[2,  3593] Training loss: 1.840
[2,  3594] Training loss: 1.840
[2,  3595] Training loss: 1.841
[2,  3596] Training loss: 1.841
[2,  3597] Training loss: 1.841
[2,  3598] Training loss: 1.841
[2,  3599] Training loss: 1.841
[2,  3600] Training loss: 1.841
[2,  3601] Training loss: 1.840
[2,  3602] Training loss: 1.840
[2,  3603] Training loss: 1.841
[2,  3604] Training loss: 1.841
[2,  3605] Training loss: 1.840
[2,  3606] Training loss: 1.840
[2,  3607] Training loss: 1.841
[2,  3608] Training loss: 1.841
[2,  360

[2,  3842] Training loss: 1.845
[2,  3843] Training loss: 1.845
[2,  3844] Training loss: 1.844
[2,  3845] Training loss: 1.844
[2,  3846] Training loss: 1.845
[2,  3847] Training loss: 1.845
[2,  3848] Training loss: 1.845
[2,  3849] Training loss: 1.845
[2,  3850] Training loss: 1.845
[2,  3851] Training loss: 1.845
[2,  3852] Training loss: 1.845
[2,  3853] Training loss: 1.845
[2,  3854] Training loss: 1.845
[2,  3855] Training loss: 1.845
[2,  3856] Training loss: 1.845
[2,  3857] Training loss: 1.845
[2,  3858] Training loss: 1.845
[2,  3859] Training loss: 1.844
[2,  3860] Training loss: 1.845
[2,  3861] Training loss: 1.844
[2,  3862] Training loss: 1.845
[2,  3863] Training loss: 1.845
[2,  3864] Training loss: 1.844
[2,  3865] Training loss: 1.844
[2,  3866] Training loss: 1.844
[2,  3867] Training loss: 1.844
[2,  3868] Training loss: 1.844
[2,  3869] Training loss: 1.844
[2,  3870] Training loss: 1.844
[2,  3871] Training loss: 1.845
[2,  3872] Training loss: 1.845
[2,  387

[2,  4104] Training loss: 1.847
[2,  4105] Training loss: 1.847
[2,  4106] Training loss: 1.847
[2,  4107] Training loss: 1.847
[2,  4108] Training loss: 1.847
[2,  4109] Training loss: 1.847
[2,  4110] Training loss: 1.847
[2,  4111] Training loss: 1.847
[2,  4112] Training loss: 1.847
[2,  4113] Training loss: 1.847
[2,  4114] Training loss: 1.847
[2,  4115] Training loss: 1.847
[2,  4116] Training loss: 1.846
[2,  4117] Training loss: 1.846
[2,  4118] Training loss: 1.846
[2,  4119] Training loss: 1.845
[2,  4120] Training loss: 1.845
[2,  4121] Training loss: 1.845
[2,  4122] Training loss: 1.845
[2,  4123] Training loss: 1.845
[2,  4124] Training loss: 1.845
[2,  4125] Training loss: 1.845
[2,  4126] Training loss: 1.845
[2,  4127] Training loss: 1.845
[2,  4128] Training loss: 1.845
[2,  4129] Training loss: 1.845
[2,  4130] Training loss: 1.845
[2,  4131] Training loss: 1.845
[2,  4132] Training loss: 1.845
[2,  4133] Training loss: 1.845
[2,  4134] Training loss: 1.845
[2,  413

[2,  4368] Training loss: 1.848
[2,  4369] Training loss: 1.848
[2,  4370] Training loss: 1.848
[2,  4371] Training loss: 1.848
[2,  4372] Training loss: 1.848
[2,  4373] Training loss: 1.848
[2,  4374] Training loss: 1.848
[2,  4375] Training loss: 1.848
[2,  4376] Training loss: 1.848
[2,  4377] Training loss: 1.848
[2,  4378] Training loss: 1.847
[2,  4379] Training loss: 1.847
[2,  4380] Training loss: 1.847
[2,  4381] Training loss: 1.847
[2,  4382] Training loss: 1.847
[2,  4383] Training loss: 1.847
[2,  4384] Training loss: 1.847
[2,  4385] Training loss: 1.847
[2,  4386] Training loss: 1.846
[2,  4387] Training loss: 1.847
[2,  4388] Training loss: 1.846
[2,  4389] Training loss: 1.846
[2,  4390] Training loss: 1.846
[2,  4391] Training loss: 1.846
[2,  4392] Training loss: 1.846
[2,  4393] Training loss: 1.847
[2,  4394] Training loss: 1.846
[2,  4395] Training loss: 1.846
[2,  4396] Training loss: 1.847
[2,  4397] Training loss: 1.847
[2,  4398] Training loss: 1.847
[2,  439

[2,  4632] Training loss: 1.849
[2,  4633] Training loss: 1.849
[2,  4634] Training loss: 1.849
[2,  4635] Training loss: 1.849
[2,  4636] Training loss: 1.849
[2,  4637] Training loss: 1.849
[2,  4638] Training loss: 1.849
[2,  4639] Training loss: 1.849
[2,  4640] Training loss: 1.849
[2,  4641] Training loss: 1.849
[2,  4642] Training loss: 1.848
[2,  4643] Training loss: 1.848
[2,  4644] Training loss: 1.848
[2,  4645] Training loss: 1.848
[2,  4646] Training loss: 1.848
[2,  4647] Training loss: 1.848
[2,  4648] Training loss: 1.848
[2,  4649] Training loss: 1.848
[2,  4650] Training loss: 1.848
[2,  4651] Training loss: 1.848
[2,  4652] Training loss: 1.848
[2,  4653] Training loss: 1.848
[2,  4654] Training loss: 1.848
[2,  4655] Training loss: 1.848
[2,  4656] Training loss: 1.848
[2,  4657] Training loss: 1.848
[2,  4658] Training loss: 1.848
[2,  4659] Training loss: 1.848
[2,  4660] Training loss: 1.848
[2,  4661] Training loss: 1.848
[2,  4662] Training loss: 1.848
[2,  466

[2,  4896] Training loss: 1.845
[2,  4897] Training loss: 1.845
[2,  4898] Training loss: 1.844
[2,  4899] Training loss: 1.844
[2,  4900] Training loss: 1.844
[2,  4901] Training loss: 1.844
[2,  4902] Training loss: 1.844
[2,  4903] Training loss: 1.844
[2,  4904] Training loss: 1.845
[2,  4905] Training loss: 1.845
[2,  4906] Training loss: 1.845
[2,  4907] Training loss: 1.845
[2,  4908] Training loss: 1.845
[2,  4909] Training loss: 1.845
[2,  4910] Training loss: 1.845
[2,  4911] Training loss: 1.845
[2,  4912] Training loss: 1.845
[2,  4913] Training loss: 1.845
[2,  4914] Training loss: 1.845
[2,  4915] Training loss: 1.844
[2,  4916] Training loss: 1.844
[2,  4917] Training loss: 1.844
[2,  4918] Training loss: 1.845
[2,  4919] Training loss: 1.845
[2,  4920] Training loss: 1.844
[2,  4921] Training loss: 1.844
[2,  4922] Training loss: 1.844
[2,  4923] Training loss: 1.844
[2,  4924] Training loss: 1.844
[2,  4925] Training loss: 1.844
[2,  4926] Training loss: 1.844
[2,  492

[2,  5160] Training loss: 1.843
[2,  5161] Training loss: 1.843
[2,  5162] Training loss: 1.843
[2,  5163] Training loss: 1.843
[2,  5164] Training loss: 1.843
[2,  5165] Training loss: 1.843
[2,  5166] Training loss: 1.843
[2,  5167] Training loss: 1.843
[2,  5168] Training loss: 1.843
[2,  5169] Training loss: 1.843
[2,  5170] Training loss: 1.843
[2,  5171] Training loss: 1.843
[2,  5172] Training loss: 1.843
[2,  5173] Training loss: 1.843
[2,  5174] Training loss: 1.843
[2,  5175] Training loss: 1.843
[2,  5176] Training loss: 1.843
[2,  5177] Training loss: 1.843
[2,  5178] Training loss: 1.843
[2,  5179] Training loss: 1.843
[2,  5180] Training loss: 1.843
[2,  5181] Training loss: 1.843
[2,  5182] Training loss: 1.843
[2,  5183] Training loss: 1.843
[2,  5184] Training loss: 1.843
[2,  5185] Training loss: 1.843
[2,  5186] Training loss: 1.843
[2,  5187] Training loss: 1.842
[2,  5188] Training loss: 1.843
[2,  5189] Training loss: 1.842
[2,  5190] Training loss: 1.842
[2,  519

[2,  5424] Training loss: 1.841
[2,  5425] Training loss: 1.841
[2,  5426] Training loss: 1.841
[2,  5427] Training loss: 1.841
[2,  5428] Training loss: 1.841
[2,  5429] Training loss: 1.841
[2,  5430] Training loss: 1.841
[2,  5431] Training loss: 1.841
[2,  5432] Training loss: 1.842
[2,  5433] Training loss: 1.842
[2,  5434] Training loss: 1.842
[2,  5435] Training loss: 1.841
[2,  5436] Training loss: 1.841
[2,  5437] Training loss: 1.841
[2,  5438] Training loss: 1.841
[2,  5439] Training loss: 1.841
[2,  5440] Training loss: 1.841
[2,  5441] Training loss: 1.841
[2,  5442] Training loss: 1.841
[2,  5443] Training loss: 1.841
[2,  5444] Training loss: 1.841
[2,  5445] Training loss: 1.841
[2,  5446] Training loss: 1.841
[2,  5447] Training loss: 1.841
[2,  5448] Training loss: 1.841
[2,  5449] Training loss: 1.841
[2,  5450] Training loss: 1.841
[2,  5451] Training loss: 1.841
[2,  5452] Training loss: 1.841
[2,  5453] Training loss: 1.841
[2,  5454] Training loss: 1.841
[2,  545

[2,  5687] Training loss: 1.837
[2,  5688] Training loss: 1.837
[2,  5689] Training loss: 1.837
[2,  5690] Training loss: 1.837
[2,  5691] Training loss: 1.837
[2,  5692] Training loss: 1.837
[2,  5693] Training loss: 1.837
[2,  5694] Training loss: 1.837
[2,  5695] Training loss: 1.837
[2,  5696] Training loss: 1.837
[2,  5697] Training loss: 1.837
[2,  5698] Training loss: 1.837
[2,  5699] Training loss: 1.837
[2,  5700] Training loss: 1.837
[2,  5701] Training loss: 1.837
[2,  5702] Training loss: 1.837
[2,  5703] Training loss: 1.837
[2,  5704] Training loss: 1.837
[2,  5705] Training loss: 1.837
[2,  5706] Training loss: 1.837
[2,  5707] Training loss: 1.837
[2,  5708] Training loss: 1.837
[2,  5709] Training loss: 1.838
[2,  5710] Training loss: 1.838
[2,  5711] Training loss: 1.838
[2,  5712] Training loss: 1.838
[2,  5713] Training loss: 1.838
[2,  5714] Training loss: 1.837
[2,  5715] Training loss: 1.837
[2,  5716] Training loss: 1.837
[2,  5717] Training loss: 1.837
[2,  571

[2,  5951] Training loss: 1.835
[2,  5952] Training loss: 1.835
[2,  5953] Training loss: 1.836
[2,  5954] Training loss: 1.836
[2,  5955] Training loss: 1.835
[2,  5956] Training loss: 1.835
[2,  5957] Training loss: 1.835
[2,  5958] Training loss: 1.836
[2,  5959] Training loss: 1.836
[2,  5960] Training loss: 1.836
[2,  5961] Training loss: 1.836
[2,  5962] Training loss: 1.836
[2,  5963] Training loss: 1.836
[2,  5964] Training loss: 1.836
[2,  5965] Training loss: 1.836
[2,  5966] Training loss: 1.836
[2,  5967] Training loss: 1.836
[2,  5968] Training loss: 1.836
[2,  5969] Training loss: 1.836
[2,  5970] Training loss: 1.836
[2,  5971] Training loss: 1.836
[2,  5972] Training loss: 1.836
[2,  5973] Training loss: 1.836
[2,  5974] Training loss: 1.836
[2,  5975] Training loss: 1.836
[2,  5976] Training loss: 1.835
[2,  5977] Training loss: 1.836
[2,  5978] Training loss: 1.836
[2,  5979] Training loss: 1.835
[2,  5980] Training loss: 1.836
[2,  5981] Training loss: 1.836
[2,  598

[2,  6215] Training loss: 1.841
[2,  6216] Training loss: 1.841
[2,  6217] Training loss: 1.840
[2,  6218] Training loss: 1.840
[2,  6219] Training loss: 1.840
[2,  6220] Training loss: 1.840
[2,  6221] Training loss: 1.840
[2,  6222] Training loss: 1.840
[2,  6223] Training loss: 1.840
[2,  6224] Training loss: 1.840
[2,  6225] Training loss: 1.840
[2,  6226] Training loss: 1.840
[2,  6227] Training loss: 1.840
[2,  6228] Training loss: 1.840
[2,  6229] Training loss: 1.840
[2,  6230] Training loss: 1.840
[2,  6231] Training loss: 1.840
[2,  6232] Training loss: 1.840
[2,  6233] Training loss: 1.840
[2,  6234] Training loss: 1.840
[2,  6235] Training loss: 1.840
[2,  6236] Training loss: 1.840
[2,  6237] Training loss: 1.840
[2,  6238] Training loss: 1.841
[2,  6239] Training loss: 1.840
[2,  6240] Training loss: 1.840
[2,  6241] Training loss: 1.840
[2,  6242] Training loss: 1.841
[2,  6243] Training loss: 1.841
[2,  6244] Training loss: 1.841
[2,  6245] Training loss: 1.841
[2,  624

[2,  6479] Training loss: 1.840
[2,  6480] Training loss: 1.840
[2,  6481] Training loss: 1.840
[2,  6482] Training loss: 1.840
[2,  6483] Training loss: 1.840
[2,  6484] Training loss: 1.840
[2,  6485] Training loss: 1.840
[2,  6486] Training loss: 1.840
[2,  6487] Training loss: 1.840
[2,  6488] Training loss: 1.840
[2,  6489] Training loss: 1.840
[2,  6490] Training loss: 1.840
[2,  6491] Training loss: 1.840
[2,  6492] Training loss: 1.840
[2,  6493] Training loss: 1.840
[2,  6494] Training loss: 1.840
[2,  6495] Training loss: 1.840
[2,  6496] Training loss: 1.840
[2,  6497] Training loss: 1.840
[2,  6498] Training loss: 1.840
[2,  6499] Training loss: 1.840
[2,  6500] Training loss: 1.840
[2,  6501] Training loss: 1.840
[2,  6502] Training loss: 1.840
[2,  6503] Training loss: 1.840
[2,  6504] Training loss: 1.840
[2,  6505] Training loss: 1.840
[2,  6506] Training loss: 1.840
[2,  6507] Training loss: 1.840
[2,  6508] Training loss: 1.840
[2,  6509] Training loss: 1.840
[2,  651

[2,  6743] Training loss: 1.842
[2,  6744] Training loss: 1.842
[2,  6745] Training loss: 1.842
[2,  6746] Training loss: 1.843
[2,  6747] Training loss: 1.843
[2,  6748] Training loss: 1.843
[2,  6749] Training loss: 1.843
[2,  6750] Training loss: 1.843
[2,  6751] Training loss: 1.843
[2,  6752] Training loss: 1.843
[2,  6753] Training loss: 1.843
[2,  6754] Training loss: 1.843
[2,  6755] Training loss: 1.843
[2,  6756] Training loss: 1.843
[2,  6757] Training loss: 1.843
[2,  6758] Training loss: 1.843
[2,  6759] Training loss: 1.843
[2,  6760] Training loss: 1.843
[2,  6761] Training loss: 1.843
[2,  6762] Training loss: 1.843
[2,  6763] Training loss: 1.843
[2,  6764] Training loss: 1.843
[2,  6765] Training loss: 1.843
[2,  6766] Training loss: 1.843
[2,  6767] Training loss: 1.843
[2,  6768] Training loss: 1.842
[2,  6769] Training loss: 1.842
[2,  6770] Training loss: 1.842
[2,  6771] Training loss: 1.842
[2,  6772] Training loss: 1.842
[2,  6773] Training loss: 1.842
[2,  677

[2,  7007] Training loss: 1.840
[2,  7008] Training loss: 1.840
[2,  7009] Training loss: 1.840
[2,  7010] Training loss: 1.840
[2,  7011] Training loss: 1.840
[2,  7012] Training loss: 1.840
[2,  7013] Training loss: 1.840
[2,  7014] Training loss: 1.840
[2,  7015] Training loss: 1.840
[2,  7016] Training loss: 1.840
[2,  7017] Training loss: 1.840
[2,  7018] Training loss: 1.840
[2,  7019] Training loss: 1.840
[2,  7020] Training loss: 1.841
[2,  7021] Training loss: 1.841
[2,  7022] Training loss: 1.840
[2,  7023] Training loss: 1.840
[2,  7024] Training loss: 1.840
[2,  7025] Training loss: 1.840
[2,  7026] Training loss: 1.840
[2,  7027] Training loss: 1.840
[2,  7028] Training loss: 1.841
[2,  7029] Training loss: 1.840
[2,  7030] Training loss: 1.840
[2,  7031] Training loss: 1.840
[2,  7032] Training loss: 1.840
[2,  7033] Training loss: 1.841
[2,  7034] Training loss: 1.841
[2,  7035] Training loss: 1.840
[2,  7036] Training loss: 1.840
[2,  7037] Training loss: 1.840
[2,  703

[2,  7271] Training loss: 1.842
[2,  7272] Training loss: 1.842
[2,  7273] Training loss: 1.842
[2,  7274] Training loss: 1.842
[2,  7275] Training loss: 1.842
[2,  7276] Training loss: 1.843
[2,  7277] Training loss: 1.843
[2,  7278] Training loss: 1.843
[2,  7279] Training loss: 1.843
[2,  7280] Training loss: 1.843
[2,  7281] Training loss: 1.843
[2,  7282] Training loss: 1.842
[2,  7283] Training loss: 1.843
[2,  7284] Training loss: 1.842
[2,  7285] Training loss: 1.842
[2,  7286] Training loss: 1.842
[2,  7287] Training loss: 1.842
[2,  7288] Training loss: 1.842
[2,  7289] Training loss: 1.843
[2,  7290] Training loss: 1.843
[2,  7291] Training loss: 1.843
[2,  7292] Training loss: 1.843
[2,  7293] Training loss: 1.843
[2,  7294] Training loss: 1.843
[2,  7295] Training loss: 1.843
[2,  7296] Training loss: 1.843
[2,  7297] Training loss: 1.843
[2,  7298] Training loss: 1.843
[2,  7299] Training loss: 1.843
[2,  7300] Training loss: 1.843
[2,  7301] Training loss: 1.844
[2,  730

[2,  7530] Training loss: 1.844
[2,  7531] Training loss: 1.844
[2,  7532] Training loss: 1.844
[2,  7533] Training loss: 1.844
[2,  7534] Training loss: 1.844
[2,  7535] Training loss: 1.844
[2,  7536] Training loss: 1.845
[2,  7537] Training loss: 1.844
[2,  7538] Training loss: 1.844
[2,  7539] Training loss: 1.844
[2,  7540] Training loss: 1.845
[2,  7541] Training loss: 1.844
[2,  7542] Training loss: 1.844
[2,  7543] Training loss: 1.845
[2,  7544] Training loss: 1.845
[2,  7545] Training loss: 1.844
[2,  7546] Training loss: 1.845
[2,  7547] Training loss: 1.845
[2,  7548] Training loss: 1.844
[2,  7549] Training loss: 1.844
[2,  7550] Training loss: 1.844
[2,  7551] Training loss: 1.844
[2,  7552] Training loss: 1.844
[2,  7553] Training loss: 1.844
[2,  7554] Training loss: 1.844
[2,  7555] Training loss: 1.844
[2,  7556] Training loss: 1.844
[2,  7557] Training loss: 1.844
[2,  7558] Training loss: 1.844
[2,  7559] Training loss: 1.844
[2,  7560] Training loss: 1.844
[2,  756

[2,  7794] Training loss: 1.846
[2,  7795] Training loss: 1.846
[2,  7796] Training loss: 1.846
[2,  7797] Training loss: 1.846
[2,  7798] Training loss: 1.845
[2,  7799] Training loss: 1.845
[2,  7800] Training loss: 1.846
[2,  7801] Training loss: 1.846
[2,  7802] Training loss: 1.846
[2,  7803] Training loss: 1.846
[2,  7804] Training loss: 1.846
[2,  7805] Training loss: 1.846
[2,  7806] Training loss: 1.846
[2,  7807] Training loss: 1.846
[2,  7808] Training loss: 1.846
[2,  7809] Training loss: 1.846
[2,  7810] Training loss: 1.846
[2,  7811] Training loss: 1.846
[2,  7812] Training loss: 1.846
[2,  7813] Training loss: 1.846
[2,  7814] Training loss: 1.846
[2,  7815] Training loss: 1.846
[2,  7816] Training loss: 1.846
[2,  7817] Training loss: 1.846
[2,  7818] Training loss: 1.846
[2,  7819] Training loss: 1.846
[2,  7820] Training loss: 1.846
[2,  7821] Training loss: 1.846
[2,  7822] Training loss: 1.846
[2,  7823] Training loss: 1.846
[2,  7824] Training loss: 1.846
[2,  782

[2,  8058] Training loss: 1.847
[2,  8059] Training loss: 1.847
[2,  8060] Training loss: 1.847
[2,  8061] Training loss: 1.847
[2,  8062] Training loss: 1.847
[2,  8063] Training loss: 1.847
[2,  8064] Training loss: 1.847
[2,  8065] Training loss: 1.847
[2,  8066] Training loss: 1.847
[2,  8067] Training loss: 1.847
[2,  8068] Training loss: 1.847
[2,  8069] Training loss: 1.847
[2,  8070] Training loss: 1.847
[2,  8071] Training loss: 1.847
[2,  8072] Training loss: 1.847
[2,  8073] Training loss: 1.847
[2,  8074] Training loss: 1.847
[2,  8075] Training loss: 1.847
[2,  8076] Training loss: 1.848
[2,  8077] Training loss: 1.848
[2,  8078] Training loss: 1.848
[2,  8079] Training loss: 1.848
[2,  8080] Training loss: 1.847
[2,  8081] Training loss: 1.848
[2,  8082] Training loss: 1.848
[2,  8083] Training loss: 1.848
[2,  8084] Training loss: 1.848
[2,  8085] Training loss: 1.847
[2,  8086] Training loss: 1.847
[2,  8087] Training loss: 1.847
[2,  8088] Training loss: 1.847
[2,  808

[2,  8322] Training loss: 1.847
[2,  8323] Training loss: 1.847
[2,  8324] Training loss: 1.847
[2,  8325] Training loss: 1.847
[2,  8326] Training loss: 1.847
[2,  8327] Training loss: 1.847
[2,  8328] Training loss: 1.847
[2,  8329] Training loss: 1.847
[2,  8330] Training loss: 1.847
[2,  8331] Training loss: 1.847
[2,  8332] Training loss: 1.847
[2,  8333] Training loss: 1.847
[2,  8334] Training loss: 1.847
[2,  8335] Training loss: 1.847
[2,  8336] Training loss: 1.847
[2,  8337] Training loss: 1.846
[2,  8338] Training loss: 1.846
[2,  8339] Training loss: 1.847
[2,  8340] Training loss: 1.847
[2,  8341] Training loss: 1.846
[2,  8342] Training loss: 1.846
[2,  8343] Training loss: 1.846
[2,  8344] Training loss: 1.846
[2,  8345] Training loss: 1.846
[2,  8346] Training loss: 1.846
[2,  8347] Training loss: 1.846
[2,  8348] Training loss: 1.846
[2,  8349] Training loss: 1.846
[2,  8350] Training loss: 1.846
[2,  8351] Training loss: 1.846
[2,  8352] Training loss: 1.846
[2,  835

In [ ]:
# def print_stats(epoch, names, values):
#     print_str = "{}: {:3d}, ".format("epoch",epoch)
#     print_str += ', '.join(("{}: {:.6f}".format(n, v) for (n, v) in zip(names, values)))
#     print(print_str)  

In [56]:
net1.parameters

<bound method Module.parameters of Net (
  (embs): ModuleList (
    (0): Embedding(57106, 10)
    (1): Embedding(448, 10)
    (2): Embedding(64, 10)
    (3): Embedding(24, 10)
    (4): Embedding(7, 10)
    (5): Embedding(52, 10)
  )
  (lin1): Linear (81 -> 500)
  (relu): ReLU ()
  (lin2): Linear (500 -> 3422)
  (soft): Softmax ()
  (bn): BatchNorm1d(21, eps=1e-05, momentum=0.1, affine=True)
  (lin3): Linear (3422 -> 2)
)>

In [238]:
# for i, data in enumerate(test_loader, 0):
#     xcat_test, xcont_test = data      
#     test_pred = net1(V(xcat_test), V(xcont_test))

In [60]:
xcat_test, xcont_test = test_dataset[:]
test_pred = net1(V(T(xcat_test)), V(T(xcont_test)))

In [61]:
test_pred

Variable containing:
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.1525  -8.3958
 40.152